### ISSUE TITLE
UX after generating an app needs improvement

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-docs#108]
When you finish generating an app, it shows the message "To start your feathers server run `npm start`."  Since the cli leaves you in a `feathers$` prompt, that won't work.  We could update the docs or update the generator to show a different message, but the guide doesn't currently reflect exactly what the user is going to experience.  It's not that big of a deal, but it's a little detail that some might appreciate.  Another option might be to have the cli automatically exit after it finishes.

```
Woot! We've created your "donejs-feathers-chat" app!
To start your feathers server run `npm start`.
feathers$ npm start

  Invalid Command. Showing Help:

  Commands:

    help [command...]     Provides help for a given command.
    exit                  Exits application.
    generate              alias for generate app
    generate app          generate new application
    generate hook         generate new hook
    generate middleware   generate new middleware
    generate model        generate new model
    generate service      generate new service
    generate plugin       generate new plugin

feathers$ 
```

**Comment by derek-watson** [comment]
Should the cli exit after each command? That's more traditional than the interactive shell thing.

**Comment by marshallswain** [comment]
@derek-watson that might make the most sense.  Can you make it do that?

**Comment by derek-watson** [comment]
@marshallswain yep, done.
