### ISSUE TITLE
About services

### ISSUE THREAD

**Issue by anhldbk** [feathersjs/feathers-docs#130]
The document In the section about [Services](http://docs.feathersjs.com/services/readme.html#) contains this info

`Adding query parameters, e.g. localhost:3030/messages?read=false will return this:`

But the demo service doesn't provide any `find` method. So it will not return any result like: 
```js
[{
  "id": 1,
  "read": false,
  "text": "Feathers is great!",
  "createdAt": 1458490631911
}]
```

**Comment by daffl** [comment]
That  is indeed true. I removed the section since that behaviour is documented in the database section.
