### ISSUE TITLE
Batching of emit events

### ISSUE THREAD

**Issue by ballwood** [feathersjs/feathers-docs#147]
Hi,

I'm writing an application that will do CRUD operations to a large number of records at a certain interval. I can't see in the documentation if there's any way to emit an event with multiple object changes at once instead of emitting the seperate events for each object1, object2, object3 on modification (I'm using redux so don't want to continually modify the state for each event as it will fire my heavy selectors often). Is this possible at all?

**Comment by daffl** [comment]
Feathers will always send all events individually but I don't think it would be too hard to implement batching on the client with custom batching in a timeout something like this: 

```js
let timeout = null;
let createdData = [];

function dispatchEvents() {
  // do something here with createdData
}

app.service('myservice').on('created', data => {
  createdData.push(data);

  if(!timeout) {
    timeout = setTimeout(() => { 
      dispatchEvents();
      createdData = [];
      timeout = null;
    }, 200);
  }
});
```

**Comment by daffl** [comment]
I'm going to close this. We may need batched emits on the server at one point but so far sockets have been performant enough to not cause any issues and I think my solution should at least help for your specific problem.
