### ISSUE TITLE
Missing chat-app component initalization in the Vue chat example

### ISSUE THREAD

**Issue by tryy3** [feathersjs/feathers-docs#151]
I know the Vue.js chat example was released yesterday. But when I was playing around with my own vue.js/feathers app.

I wanted to check the vue.js chat example and I noticed that in the example at vue.js https://github.com/feathersjs/feathers-chat/tree/master/public/vue-chat the chat-app is being initalized on line 53 in app.js

But on the guide at http://docs.feathersjs.com/frameworks/vuejs.html I can't see anywhere that you should initalize it.

I haven't really tested the guide myself, but when I was playing around with components on my own, I noticed that you need to initalize them with a template id.

I just started learning vue.js so I could be wrong with components needing to be initialized, so if I am wrong, sorry for taking your time.
I also didn't want to make a pull request incase @niallobrien was working on it and since he wrote it, he has a better idea where the initalization should be in the doc.

**Comment by niallobrien** [comment]
Good catch, thanks for letting me know. I'll push a fix later today.

**Comment by tryy3** [comment]
Closing this, as its been resolved by #152
