### ISSUE TITLE
Write a guide for creating plugins

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-docs#155]

**Comment by thejones** [comment]
I started on this & there should be a Pull Request (https://github.com/feathersjs/feathers-docs/pull/160) . I have no idea what I am talking about so feel free to edit/make changes.

**Comment by thejones** [comment]
@daffl do you want to keep this open for your modifications to the guide?

**Comment by daffl** [comment]
I'll make those some time later but I think we can totally close this one. Thanks a bunch again!

**Comment by ekryski** [comment]
Yeah! Thanks @thejones! Nice work!
