### ISSUE TITLE
PDF version lacks font icons

### ISSUE THREAD

**Issue by j2L4e** [feathersjs/feathers-docs#175]
Example: page 39 of the docs PDF

![image](https://cloud.githubusercontent.com/assets/13417122/15540253/a5c3e1f6-2286-11e6-9e57-e7e77f59f3ca.png)

**Comment by daffl** [comment]
This looks like a [GitBook issue](https://github.com/GitbookIO/gitbook/issues/762). I guess the only thing we could do would be to change it to other unicode characters.

**Comment by marshallswain** [comment]
We can replace them with images, which show up nicely in all versions.

**Comment by marshallswain** [comment]
I tried using the advanced-emoji plugin, but the output still doesn't show some of the emoji characters, so I removed it.

**Comment by marshallswain** [comment]
No luck for PDFs & eBooks.  Gitbook doesn't support putting emoji in tables, which defeats our purpose. Closing.

**Comment by daffl** [comment]
I think the plan was to move "vs articles" to the blog. Should we keep the comparison table at all?

**Comment by corymsmith** [comment]
I think is something that people would expect on the site or would look for and always ask about so putting it on Medium may not be the best idea. Better to keep it front and center? Or maybe just add some items to the FAQ around that

**Comment by marshallswain** [comment]
Yeah.  Just the comparison matrix ought to stay, imo.

**Comment by daffl** [comment]
The problem in the docs is keeping the comparisons up to date . On the blog it would still show up on searches and we can link to it but I think it would be more acceptable if the information is out of date.
