### ISSUE TITLE
Current doc tutorial has incorrect info

### ISSUE THREAD

**Issue by genyded** [feathersjs/feathers-docs#178]
In the tutorial section [here](http://docs.feathersjs.com/getting-started/user-management.html) is incorrect. 

The part that states:

`There we can log in with the information we used to sign up and will get redirected to chat.html which currently shows authentication success page with the JWT.`

...is not correct because a chat.html page is never created (or at least not if your following the docs) with instructions on how to set it up to display success with JWT, so a 404 is returned after login instead.

**Comment by daffl** [comment]
It should still show a [fallback success page](https://github.com/feathersjs/feathers-authentication/blob/master/src/public/auth-success.html) provided by `feathers-authentication`.

**Comment by genyded** [comment]
Well I followed it vebatim and get a 404 no biggie though... Can still move forward. But furthe in... The Vue client stuff throws several errors. It also missing some css files referenced.

**Comment by daffl** [comment]
I'll double check the 404. 

The Vue guide was referencing the relative path from the example app (https://github.com/feathersjs/feathers-chat/tree/master/public/vue-chat). I fixed the CSS links. What are the errors?

**Comment by genyded** [comment]
Index.html has the following...

<details>
<summary>index.html</summary>
```html
<link rel="stylesheet" href="//cdn.rawgit.com/feathersjs/feathers-chat/v0.1.0/public/base.css">
<link rel="stylesheet" href="//cdn.rawgit.com/feathersjs/feathers-chat/v0.1.0/public/chat.css">
```
</details>

...but chat.html has...

<details>
<summary>chat.html</summary>
```html
<!-- these do not exist? -->
<link rel="stylesheet" href="../base.css"> 
<link rel="stylesheet" href="../chat.css">
```
</details>

Also (possibly another path issue), running it after following the docs [here](http://docs.feathersjs.com/frameworks/vuejs.html) returns the following errors:

<details>
<summary>console errors</summary>
```
vue.js:991 [Vue warn]: Unknown custom element: <chat-app> - did you register the component correctly? For recursive components, make sure to provide the "name" option.warn @ vue.js:991checkComponentAttr @ vue.js:1560checkComponent @ vue.js:7211compileElement @ vue.js:7006compileNode @ vue.js:6966compileNodeList @ vue.js:7149compile @ vue.js:6752FragmentFactory @ vue.js:3875insert @ vue.js:4529update @ vue.js:4515_update @ vue.js:8194Watcher.run @ vue.js:3279runBatcherQueue @ vue.js:3007flushBatcherQueue @ vue.js:2983nextTickHandler @ vue.js:438
vue.js:991 [Vue warn]: Unknown custom element: <user-list> - did you register the component correctly? For recursive components, make sure to provide the "name" option.warn @ vue.js:991checkComponentAttr @ vue.js:1560checkComponent @ vue.js:7211compileElement @ vue.js:7006compileNode @ vue.js:6966compileNodeList @ vue.js:7149compileNodeList @ vue.js:7150compile @ vue.js:6752FragmentFactory @ vue.js:3875insert @ vue.js:4529update @ vue.js:4515_update @ vue.js:8194Watcher.run @ vue.js:3279runBatcherQueue @ vue.js:3007flushBatcherQueue @ vue.js:2983nextTickHandler @ vue.js:438
vue.js:991 [Vue warn]: Unknown custom element: <message-list> - did you register the component correctly? For recursive components, make sure to provide the "name" option.warn @ vue.js:991checkComponentAttr @ vue.js:1560checkComponent @ vue.js:7211compileElement @ vue.js:7006compileNode @ vue.js:6966compileNodeList @ vue.js:7149compileNodeList @ vue.js:7150compile @ vue.js:6752FragmentFactory @ vue.js:3875insert @ vue.js:4529update @ vue.js:4515_update @ vue.js:8194Watcher.run @ vue.js:3279runBatcherQueue @ vue.js:3007flushBatcherQueue @ vue.js:2983nextTickHandler @ vue.js:438
vue.js:991 [Vue warn]: Unknown custom element: <compose-message> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```
</details>

**Comment by genyded** [comment]
OK - you fixed the css stuff. I think the other issue (the errors) is because the docs says to create 'public/vue-chat/app.js', but the reference in chat.html is toapp.js in the public root - not under a vue-chat folder... `<script src="app.js"></script>` - that is line 98 in chat.html. If I move app.js to  public root - it works. This can be close unless you want to leave it open to change the app.js path in one place or the other. Thanks for the help and quick responses David!

**Comment by daffl** [comment]
Thank you for reporting this. I also fixed the `app.js` reference so the tutorial is hopefully working again now.
