### ISSUE TITLE
Document params.provider in hooks page.

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-docs#18]

**Comment by daffl** [comment]
Is there a specific reason? `params.provider` should be already documented in each provider documentation page.

**Comment by marshallswain** [comment]
Only because the hooks page covers what's available in the hooks.  I think it ought to be mentioned in brief.

**Comment by daffl** [comment]
This is documented now in the `disable` hook at http://docs.feathersjs.com/hooks/bundled.html
