### ISSUE TITLE
Write a guide on deploying to CloudFoundry

### ISSUE THREAD

**Issue by combsco** [feathersjs/feathers-docs#187]
I've already had success deploying my app to a CF instance. Just thought those working with this type of platform would like a guide on how to do it also.

**Comment by marshallswain** [comment]
I've been meaning to do this, but are you volunteering, now?  :)

**Comment by ekryski** [comment]
@combsco you down for writing a guide?! Would be shweeet 😁

**Comment by combsco** [comment]
Yeah @marshallswain and @ekryski ... I'll give it a go. Do we have any basic template out there I can model after...?

**Comment by ekryski** [comment]
@combsco Awesome! I'll put up the Heroku guide this week (and possibly digital ocean) and then that will hopefully be enough to go off of. If you have the cycles earlier this week, feel to take a stab and we can help revise if it needs it.

In my mind just showing how to deploy an app in it's basic form with one instance is already a great start. The next step would be how to show multiple instances (ie. a cluster).

**Comment by benwalks** [comment]
@ekryski I can't wait for the Heroku and Digital Ocean guides 😄

**Comment by ekryski** [comment]
@combsco @marshallswain anyone still working on this? If not then I'm going to close as the rest of the core team is unlikely to do this in the near term. Happy to re-open if it comes up again or someone from the community wants to contribute but we're more focused on Heroku.

**Comment by ekryski** [comment]
okay... I'm going to close this. If someone wants to take a stab. Happy to re-open.
