### ISSUE TITLE
Add Gitbook Versions Plugin

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-docs#193]
Now that people are using Feathers in production and core V3 changes are likely to have breaking changes we should version the docs. Looks like we can do it via Gitbook still. http://developer.gitbook.com/books/versions/

**Comment by daffl** [comment]
As we discussed, since the docs can be browsed through GitHub I think before a new release we can create a [tag](https://github.com/feathersjs/feathers-docs/releases) for the current version  and just link to that.

**Comment by ekryski** [comment]
Absolutely. If we are tagging the versions we can actually add this plugin: https://plugins.gitbook.com/plugin/versions

**Comment by marshallswain** [comment]
@ekryski I enabled that plugin, but it dramatically slowed down the docs loading time, so I removed it.  I think we should just manually link to the repo.  Closing this for now.

**Comment by ekryski** [comment]
ok cool. Thanks for trying it out @marshallswain!
