### ISSUE TITLE
Typo in Your First App tutorial

### ISSUE THREAD

**Issue by lfung** [feathersjs/feathers-docs#195]
There is a small typo, but since there are many folders involved, it can lead to confusion.  From the Serializing Messages section, http://docs.feathersjs.com/getting-started/formatting-and-hooks.html#serializing-messages

There is a reference to a message folder, which should instead be "messages".  Here is the sentence:

"We need to make a small change to our src/services/**message**/hooks/index.js file so that it now looks like this:"

**Comment by daffl** [comment]
That is true indeed. There is an "Edit this page" button at the top which links to https://github.com/feathersjs/feathers-docs/edit/master/getting-started/user-management.md. If you make the edit and submit it as a pull request it would be very much appreciated.
