### ISSUE TITLE
Some places are wrong/missing in Angular 2 doc

### ISSUE THREAD

**Issue by Hongbo-Miao** [feathersjs/feathers-docs#211]
http://docs.feathersjs.com/frameworks/angular2.html

1.
`export class SocketService extends Service`, not sure where this `Service` is from.

2.

```
this._rest = _restService.getService('messages');
this._socket = _socketService.getService('messages');
```

getService is not implement in **feathers.service.ts**

**Comment by marshallswain** [comment]
@Hongbo-Miao, Thanks for pointing this stuff out.  We depend on the community for keeping us accurate.  If you can see how to fix it, would you mind making the corrections, here: https://github.com/feathersjs/feathers-docs/edit/master/frameworks/angular2.md?

**Comment by ekryski** [comment]
@Hongbo-Miao bump! We're less familiar with Angular2 so we'd really appreciate your help. You can easily create an instant PR by altering the linked file above. Would be much appreciated. 😄

**Comment by Hongbo-Miao** [comment]
These two issues I pointed out are related. I am not clear where is the `Service` in `export class SocketService extends Service` from.

My guess it is from feathers.js. Need it be clear, something like 

TypeScript:
`import { Service } from 'feathers.js';`

Since no typings, probably:
const Service = require('feathers.js');

But right now I don't know where is this Service exactly from.

**Comment by Hongbo-Miao** [comment]
I made the PR https://github.com/feathersjs/feathers-docs/pull/252

There is one thing that the document not clear right now and I haven't updated, it does not say anything about the `Service`.

Based on https://berndsgn.ch/angular2-and-feathersjs/, you still need write your own Service and then extend.

**Comment by Hongbo-Miao** [comment]
Another thing I didn't add is that you cannot just easily adding type `SocketIOClient.Socket` in `public socket: SocketIOClient.Socket;` because this type is special.

You need run `npm install --save-dev @types/socket.io-client`.

And also add this in your **tsconfig.json** file:

```
"types": [
  "socket.io-client"
]
```

**Comment by harangue** [comment]
This guide is very, very out of date. Angular has gone through some major revisions since then, and it's not an accurate reflection of how feathers applications should be structured these days. I recommend removing this guide permanently - hopefully I can get a chance to write a new one soon. :)

**Comment by aurerua** [comment]
I am also having trouble using this guide and ran into the same problems. There is also the problem that some snippets of code are provided without it being clear where they belong.

Until someone manages to update the guide, I support @harangue 's suggestion to remove this part from the guide.

**Comment by aurerua** [comment]
I am making good progress at trying to write my own version of the Angular2 chat app. 

It is not finished yet and is still a bit messy, but feel free to have a look if you are interested: https://github.com/aurerua/feathersjs-angular2 (feedback is welcome)

This version also deals with authentication though. So it is a bit more than what the other frameworks do in the docs. In the docs authentication is taken away from the Frameworks part and implemented as static pages. The Frameworks kick off after login (the framework is set as the path given to "successRedirect" in /config/default.json).

Once I am done, and if I manage to find a good solution to the issue #350 I can write an updated version of the docs if it is necessary. But I will definitely need someone versed in Angular 2 to review it first.

**Comment by jsgoupil** [comment]
@aurerua Thanks for that contribution on your repo. It definitely gets me started in the right direction. There are a couple of things that should be fixed before it is posted as official. I don't think I would recommend connecting to the server in the constructor of your message service for instance.

I think the authentication package is getting overhaul from what I am seeing. Not sure it is the same on the client, I am just starting on feathersjs. The "auth/local" should be written only at once spot (it's used in authenticate service, and feathers service)

**Comment by daffl** [comment]
We removed the frameworks specific guides from the documentation and will put them into blog posts so I am going to close this.
