### ISSUE TITLE
Add documentation for unit tests best practices

### ISSUE THREAD

**Issue by ms007** [feathersjs/feathers-docs#213]
I'm relative new to feathers.js and I'm having a hard time figuring out the best practices to wire up unit tests for the different parts of feathers.js. 

It would be nice to have a section about unit tests in the feathers book

**Comment by daffl** [comment]
You are right, it might help to have some documentation. I'm not entirely sure what exactly to document though other than requiring the app and calling the [service interface](http://docs.feathersjs.com/services/readme.html) you want to test (taken from 
https://github.com/feathersjs/feathers/issues/367#issuecomment-234298086 and using Mocha 3):

```js
describe('myservice', function() {
  it('runs create', function() {
    return app.service('myservice').create({ name: 'David' }).then(person => {
      assert.ok(person._id);
      assert.equal(person.name, 'David');
    });
  });
});
```

The generated app also creates some unit tests but that's really it.

**Comment by ekryski** [comment]
I think #215 that just landed should help (thanks to @jayzamazing). You can find the docs at http://docs.feathersjs.com/testing/readme.html.
