### ISSUE TITLE
MongoDB talks about NeDB? Wut.

### ISSUE THREAD

**Issue by ElegantSudo** [feathersjs/feathers-docs#214]
<img width="959" alt="screen shot 2016-08-13 at 11 18 07 am" src="https://cloud.githubusercontent.com/assets/19272022/17643954/ad7e4cf6-6147-11e6-9f33-2248577ee93d.png">

On the MongoDB page.

**Comment by daffl** [comment]
You can edit the page right at https://github.com/feathersjs/feathers-docs/edit/master/databases/mongodb.md
