### ISSUE TITLE
Combine two pages up to keep docs DRY?

### ISSUE THREAD

**Issue by rawreef** [feathersjs/feathers-docs#222]
I'd like to add a suggestion to the Getting Started page, but I notice that these two pages:
[https://docs.feathersjs.com/getting-started/quick-start.html](https://docs.feathersjs.com/getting-started/quick-start.html) and [https://docs.feathersjs.com/getting-started/scaffolding.html](https://docs.feathersjs.com/getting-started/scaffolding.html) cover some of the same ground.

Could this be DRY-ed up so I can add my suggestion to just one page? Personally I preferred the content in the Getting Started page as it was a bit more concise and got me going quicker.

**Comment by ekryski** [comment]
@rawreef thanks for the feedback. We're going to be auditing and overhauling the docs shortly so this will likely happen.

**Comment by ekryski** [comment]
Going to close this in order to track progress in #251
