### ISSUE TITLE
Documentation Inaccessible

### ISSUE THREAD

**Issue by machineghost** [feathersjs/feathers-docs#235]
Currently if you go to https://docs.feathersjs.com/ you will find ...

* a link to the tutorial
* a link to the "guides" (really just one guide)
* a link to the "getting started" readme
* a link to the page itself (the "HTML" link)
* links to other formats

What you won't find is a link to the actual API documentation (eg. https://docs.feathersjs.com/api/readme.html), which used to be there.  Could you please restore that link?

**Comment by daffl** [comment]
Several people have reported this but we were not able to reproduce. It usually worked again for everybody

- By opening  https://docs.feathersjs.com/ in an incognito window
- After clearing the cache and reloading the page

**Comment by machineghost** [comment]
Ahhh.  When I did a hard refresh (open dev tools, click and hold refresh button) it fixed things.  Thanks.
