### ISSUE TITLE
Possible error in Client Use/Feathers Client/Socket.io chapter

### ISSUE THREAD

**Issue by heymartinadams** [feathersjs/feathers-docs#237]
Possible error in chapter [**Client Use** » **Feathers Client** » **Socket.io**](https://docs.feathersjs.com/clients/socket-io.html):
`const feathers = require('feathers/client');`

Shouldn’t it be:
`const feathers = require('feathers-client');`

And is this line correct?
`const socketio = require('feathers-socketio/client');`

**Comment by marshallswain** [comment]
@heymartinadams Each main package includes the node version as the main and the client version at `<package>/client.js`  The `feathers-client` package is a convenience package that includes all of the main client libs in one.  So, technically they are all correct.  Check out the readme of `feathers-client` for reasoning behind this structure: https://github.com/feathersjs/feathers-client.

**Comment by dkebler** [comment]
but  if one loads just the feather-client package this require
`const feathers = require('feathers/client');`
throws a missing package error.

Since loading separately and the convenience package are NOT equivalent then the examples should indicate which one it works for and what to change if loading the other way.   When it comes to noobs it's not great to suggest something you know will throw an error.

Here is what I suggest although the BEST solution is to make the convenience package work the same way as installing them separately (i.e. both use `feathers/client` Why doesn't it??)

# Module Loaders

The client utilities can be used directly on the server. Just install the feathers-client convenience package.

`npm install feathers-client`

**Note**: If you opt to install all the packages separately then use

`feathers/client` in place of `feathers-client`

## Node and npm loaders

Use `require` in Nodejs or `import` in the browser if using webpack, etc 

```
const feathers = require('feathers-client');
const socketio = require('feathers-socketio/client');
const hooks = require('feathers-hooks');
const errors = require('feathers-errors'); // An object with all of the custom error types.
const auth = require('feathers-authentication-client');
const io = require('socket.io-client/dist/socket.io');

const socket = io('http://localhost:3030', {
  transports: ['websocket']
});

const feathersClient = feathers()
  .configure(socketio(socket))
  .configure(hooks())
  .configure(auth())

module.exports = feathersClient;
```

## Browserify, StealJS, and Webpack

...........
change `feathers/client` to `feathers-client` below

**Comment by marshallswain** [comment]
> Since loading separately and the convenience package are NOT equivalent
Why are they not equivalent?

**Comment by marshallswain** [comment]
That module should not be missing.  It's right here: https://github.com/feathersjs/feathers/blob/master/client.js

Keep in mind that the `lib` folder is created as part of the build, so it's not missing from the repo.

**Comment by dkebler** [comment]
I did see the /lib folder as I looked in the install in my node_modules folder and not in the github repo.

Well....actually after looking at feathers-client export why isn't the documentation for NPM like below.  You've exported all these as keys/props in the module why keep requiring just cause the packages are in node_modules as dependencies??

Bottom line (at least to me) the feather-client repo/module and it's proper use is confusing and inconsistent.

I've kinda figured it out the idiosyncracies but a noob will likely be confused or have the same issue as @heymartinadams 
```
Object.assign(_client2.default, {
  socketio: _client6.default,
  primus: _client8.default,
  rest: _client4.default,
  hooks: _feathersHooks2.default,
  authentication: _feathersAuthenticationClient2.default,
  errors: _feathersErrors2.default
});

exports.default = _client2.default;
module.exports = exports['default'];
```

```
const feathers = require('feathers-client'),
 socketio = feathers.socketio,
 hooks = feathers.hooks,
 errors = feathers.errors,
 auth = feathers.authentication

const io = require('socket.io-client/dist/socket.io');

const socket = io('http://localhost:3030', {
	transports: ['websocket']
});

const feathersClient = feathers()
  .configure(hooks())
  .configure(socketio(socket))
  .configure(auth())

module.exports = feathersClient;

**Comment by dkebler** [comment]
actually the npm/node portion of the docs is incorrect wrt the socket.io package.
The documented require is for a browser but the non dist is for node.

Should be 
```
X const io = require('socket.io-client/dist/socket.io');
const io = require('socket.io-client');
```
First gives error
correction works

see 
```
Node.JS (server-side usage)

Add socket.io-client to your package.json and then:

var socket = require('socket.io-client')('http://localhost');
socket.on('connect', function(){});
socket.on('event', function(data){});
socket.on('disconnect', function(){});
```
from 
https://github.com/socketio/socket.io-client

and my stackoverflow question
https://stackoverflow.com/questions/46626831/feathersjs-node-socket-client-not-connecting

**Comment by dkebler** [comment]
So for npm/node example how about this which is more terse and I have confirmed to work
```
const feathers = require('feathers-client')

const socket = require('socket.io-client')('http://192.168.0.51:3030', { transports: ['websocket'] })

 const feathersClient = feathers()
   .configure(feathers.hooks())
   .configure(feathers.socketio(socket))
   .configure(feathers.authentication())

module.exports = feathersClient;
```

**Comment by daffl** [comment]
That is true indeed, thank you. Not sure how the `dist/` reference for the socket.io client slipped in there, it is fixed now. Everything else should work as advertised though.

For the next version this will also become more straightforward (see https://github.com/feathersjs/feathers-client/issues/137). `feathers` itself will be usable on the client and the server and all client functionality will be in their own respective repositories (e.g. [feathers-rest-client](https://github.com/feathersjs/feathers-rest-client), `feathers-socketio-client` etc.).
