### ISSUE TITLE
Picky ambiguity in 'all' hooks?

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/feathers-docs#238]
In [before hooks](https://docs.feathersjs.com/hooks/usage.html#before-hooks) we have:

"Note: all hooks will be registered before specific hooks in that object. For the above example that means that the all hook will be added to the create service method and then the specific hook."

Perhaps `and then the specific hook` is unclear.

**Comment by daffl** [comment]
I think this should be more clear in the [new hooks documentation](https://docs.feathersjs.com/api/hooks.html) now.
