### ISSUE TITLE
Mention 'params' option on service methods is ignored on the client.

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/feathers-docs#261]
The second param in `users.create(user, { test: 'test' }, cb)` on the client is, I believe, ignored. Its still needed to position the `cb` if one is used.

Perhaps this should be mentioned under the Client section.

Is this the only difference between calls on the server and on the client?

**Comment by cklmercer** [comment]
I ran into this issue today.
After digging through the source for the client, I found that when calling services methods (e.g. "find", "get", etc.), the client is explicitly passing `params.query || {}`.

**Comment by eddyystop** [comment]
@cklmercer What you mention opens a way for the client to pass options to the service.

```javascript
// on client
service.get(id, { query: { serverOption: 'xxx' }});
// on server
service.before({
  all: hook => {
    hook.params.serverOption = hook.params.query.serverOptions;
    delete hook.params.query.serverOptions;
  }
});
```

**Comment by cklmercer** [comment]
I totally get that and am doing it might self. Was just commenting hear, because initially I was try to pass through data at the top level. It took me awhile to figure out that on this first of the following two will work on client-side, even though both work server-side.

```javascript

// Works on both
service.find({
     query: { serviceOptions }
})
```

```javascript

// Only works on server
service.find({
    serviceOptions 
})
```

**Comment by ekryski** [comment]
I've added a section to the FAQ section of the docs. https://docs.feathersjs.com/faq/readme.html#why-cant-i-pass-params-from-the-client
