### ISSUE TITLE
the 'services' Read.me only mentions the happy path

### ISSUE THREAD

**Issue by jay-at-avido** [feathersjs/feathers-docs#262]
Regarding this page:
https://docs.feathersjs.com/services/readme.html

There are some 'then' examples but no 'catch' anywhere.
Please include an example or best practice advices on how to deal with errors coming from direct service calls.

**Comment by daffl** [comment]
I'm not sure how much into detail the documentation should go about JavaScript language functionality. We'd definitely accept a pull request with an example ([edit here](https://github.com/feathersjs/feathers-docs/edit/master/services/readme.md)) though.

**Comment by daffl** [comment]
Thank you again for the suggestion @jay-at-avido. I am going to close this issue however. As I said, we would happy to accept a pull request with a note about promises `.catch` but there are many things for the team to focus on first before we can start documenting core JavaScript language features and how they work with Feathers.
