### ISSUE TITLE
Chaos text at the bottom of the each page in Chrome

### ISSUE THREAD

**Issue by Hongbo-Miao** [feathersjs/feathers-docs#268]
Chaos text at the bottom of the each page in Chrome.

Tried Chrome 56.0.2886.0 canary and 55.0.2873.4 dev. Both are same.

If it does not show in your browser, try to switch between chapters, and scroll down to bottom, you will see.

![image](https://cloud.githubusercontent.com/assets/3375461/19913721/7cec9566-a07b-11e6-8471-ec5da27e362d.png)

**Comment by daffl** [comment]
I can't reproduce this in my browser or any of the Chrome versions mentioned on [Browserstack](https://www.browserstack.com/). This might have only been intermittent, I'd try clearing my browser cache and reloading (or incognito mode).

**Comment by Hongbo-Miao** [comment]
Okay, find a way to reproduce, you can go to Frameworks -> iOS (or others), scroll down, you will see.

**Comment by Hongbo-Miao** [comment]
Thanks, I located the issue. It is because of one of my extension [Poper Blocker](https://chrome.google.com/webstore/detail/poper-blocker/bkkbcggnhapdmkeljlodobbkopceiche?hl=en) causes the page won't show well.

Weired issue. Although this page seems having no popup. I will close this now. But it will be great to fix this issue. I guess some codes are blocked by the extension.
