### ISSUE TITLE
Getting Started > Explain How to POST via Postman Better

### ISSUE THREAD

**Issue by geirman** [feathersjs/feathers-docs#274]
When I got to the point where I needed to add a message, the following curl command works...

```
$ curl 'http://localhost:3030/messages/' -H 'Content-Type: application/json' --data-binary '{ "text": "Hello Feathers!" }'
```

But, it wasn't clear how to make the same POST via Postman. Specifically, I was confused about how to represent the `--data-binary '{ "text": "Hello Feathers!" }'` bit. Would be nice to make that clarification.

**Comment by marshallswain** [comment]
I think this is fixed here: https://docs.feathersjs.com/v/auk-reorg/guides/chat/service.html#testing-the-api

@geirman does that take care of this issue?

**Comment by geirman** [comment]
A crazy cool "Run on Postman" button?! Hell yeah that works! Even better than I expected. Nice work!

**Comment by marshallswain** [comment]
Ok.  I'm going to close this.  We will be merging that in soon.  Thanks!

**Comment by kajogo777** [comment]
hello @marshallswain  i have the same question but the like provided above is not working anymore

thanks in advance

**Comment by daffl** [comment]
The current link is https://docs.feathersjs.com/guides/chat/service.html#testing-the-api
