### ISSUE TITLE
Getting Started > Confused about Feather's Client

### ISSUE THREAD

**Issue by geirman** [feathersjs/feathers-docs#275]
In the getting started guide, I came across this paragraph...

> You can also connect to the real-time API using Socket.io. The easiest way to do so is using the Feathers client. You can learn more about using Feathers on the client in the Client chapter.

I clicked on each of the links in that paragraph, but it feels like I'm falling down a rabbit hole and I'm immediately overwhelmed and lost. It's not clear how they relate or how it might be helpful to connect via a "feathers client". I recommend either making this more clear or deferring this info until a later time. Having it here, as is, I think is confusing and discouraging which are probably not the best emotions to have when getting started.

**Comment by daffl** [comment]
This has been changed in the new guides (in the [Building a frontend](https://docs.feathersjs.com/guides/chat/frontend.html)) step.
