### ISSUE TITLE
Getting Started > Oops, forgot to create the /chat.html

### ISSUE THREAD

**Issue by geirman** [feathersjs/feathers-docs#277]
After creating a user and logging in, I got a 404 because the /chat.html page was never created.

**Comment by PeterGrandcourt** [comment]
Hi Geirman,
I got exactly the same! Seems there are a few gaps in the tutorial.  Did you manage to create a useful chat. html page? 

Peter

**Comment by geirman** [comment]
Nope, I never got that far

**Comment by daffl** [comment]
You will create this page in the [framework guide](https://docs.feathersjs.com/frameworks/readme.html) of choice. The [user management](https://docs.feathersjs.com/getting-started/user-management.html) section of the getting started guide does say that:

> The last step is to change the standard success redirect to /chat.html. This page will contain the actual frontend for our chat application. Because there are so many different frameworks we won't create that page yet and instead implement it in the framework guides for your favourite framework after finishing this tutorial.

**Comment by mattwoolnough** [comment]
Further on down the page it states:

> There we can log in with the information we used to sign up and will get redirected to chat.html which currently shows authentication success page with the JWT.

Which is incorrect. The user just receives a 404 error.

**Comment by daffl** [comment]
The login and signup HTML pages have been removed in [the latest chat guide](https://docs.feathersjs.com/guides/chat/readme.html) showing a more API centric approach (client implementations can be found [here](https://github.com/feathersjs/feathers-chat/tree/master/public)).

**Comment by geirman** [comment]
Good to know. I'll put this back on my radar and make time to check it out again. Busy learning serverless + graphql + react at the moment which is challenging
