### ISSUE TITLE
Documentation for Setting up Local Authentication is outdated

### ISSUE THREAD

**Issue by kulakowka** [feathersjs/feathers-docs#28]
I found an inaccuracy in the documentation on the page: http://docs.feathersjs.com/authentication/local.html

It is written there:

> You'll notice that it currently includes the password. You really don't want it exposed, so when you're ready to secure the service, you'll need an additional feathers-hook to remove the password property from the response.

But when I run the example, the server response does not contain the password.

![2016-02-18 23 20 18](https://cloud.githubusercontent.com/assets/557190/13156953/373915bc-d696-11e5-86d7-e70dd820f7e3.png)

It seems this documentation is outdated? Or am I doing something wrong?

I have no more additional hooks for user model.

```javascript
import globalHooks from '../../../hooks';
import { hooks as auth } from 'feathers-authentication';

let before = {
  all: [],
  find: [],
  get: [],
  create: [auth.hashPassword()],
  update: [],
  patch: [],
  remove: []
};

let after = {
  all: [],
  find: [],
  get: [],
  create: [],
  update: [],
  patch: [],
  remove: []
};

export default { before, after };
```

And my `app.js` looks like:

```javascript
import { join } from 'path';
import { static as serveStatic } from 'feathers';
import favicon from 'serve-favicon';
import compress from 'compression';
import cors from 'cors';
import feathers from 'feathers';
import configuration from 'feathers-configuration';
import hooks from 'feathers-hooks';
import rest from 'feathers-rest';
import bodyParser from 'body-parser';
import socketio from 'feathers-socketio';
import authentication from 'feathers-authentication';
import middleware from './middleware';
import services from './services';

let app = feathers();

app.configure(configuration(join(__dirname, '..')))
  .use(compress())
  .options('*', cors())
  .use(cors())
  .use(favicon( join(app.get('public'), 'favicon.ico') ))
  .use('/', serveStatic( app.get('public') ))
  .use(bodyParser.json())
  .use(bodyParser.urlencoded({ extended: true }))
  .configure(hooks())
  .configure(rest())
  .configure(socketio())
  .configure(authentication( app.get('auth') ))
  .configure(services)
  .configure(middleware)


export default app;
```

**Comment by ekryski** [comment]
I just pushed a ton of updates to the authentication docs this morning. It was out dated. They are up to date now. The user returned from a successful authentication has the password removed. Thanks for reporting!

**Comment by kulakowka** [comment]
Cool! It seems I'll have to read the documentation more than once :)

**Comment by ekryski** [comment]
@kulakowka ya sorry about that. Pretty much everything in the docs is stable and has been proof-read now. Auth was the last piece. I have a couple more updates I'm working on right now but after today it should be pretty solid.

**Comment by kulakowka** [comment]
I met a small number of errors compared to other projects. That is why I chose feathersjs as the basis for my new project. Thank you for the work done. :+1:
