### ISSUE TITLE
Bug: Google Analytics Script gets rendered not executed

### ISSUE THREAD

**Issue by frank-dspeed** [feathersjs/feathers-docs#292]
https://docs.feathersjs.com/databases/mongoose.html

scroll all sliders down you will see that the google script

i tryed to fix it but i don't used this page generators a lot so sorry some one else need to look at this.

**Comment by osenvosem** [comment]
Just wanted to add this issue.
This emerges not only on mongoose page, I met this on several pages, for example here https://docs.feathersjs.com/why/philosophy.html
It also breaks pages on a tablet.

![screen shot 2016-11-23 at 13 24 04](https://cloud.githubusercontent.com/assets/6762673/20558357/b07cbf44-b180-11e6-884d-79cb60f9da64.png)

**Comment by marshallswain** [comment]
Thanks guys.  It looks like Gitbook might have changed something on their end.  We aren't ignoring this, but will swing around to it once we button up auth.  The pages at least stay usable, right?  And it wasn't showing up consistently for me, which is puzzling.

**Comment by frank-dspeed** [comment]
@marshallswain i searched for the bug also i don't found where it comes from i think its a syntax error because the script it self gets loaded in frontend on right place as script.

**Comment by daffl** [comment]
This is fixed now. It was one of the plugins setting `display: block` for some script tags.
