### ISSUE TITLE
Bug: 404 on Hooks example Mongose

### ISSUE THREAD

**Issue by frank-dspeed** [feathersjs/feathers-docs#293]
https://docs.feathersjs.com/hooks/examples.html#validation - 404 from - https://docs.feathersjs.com/databases/mongoose.html in text link called "using hooks"

**Comment by daffl** [comment]
Thanks. I removed it since that isn't really relevant anyway. Updated docs for the next release will also come with https://github.com/feathersjs/feathers-docs/pull/299.
