### ISSUE TITLE
Servises: Question

### ISSUE THREAD

**Issue by osenvosem** [feathersjs/feathers-docs#295]
Is this "ProTip" still relevant?
https://github.com/feathersjs/feathers-docs/edit/master/services/readme.md#L203-L204

`data` is passed as a separate parameter. So it seems the are no `params.data` and also `params.result` properties. I couldn't get those from inside a custom service. Or maybe I didn't understand something.

**Comment by daffl** [comment]
Thank you. That was never the case, I fixed it.

**Comment by osenvosem** [comment]
@daffl you wrote `hook.params.query`, but there is a service, not a hook.

**Comment by daffl** [comment]
Dang. Fixed.
