### ISSUE TITLE
TOC

### ISSUE THREAD

**Issue by leebenson** [feathersjs/feathers-docs#306]
I could have sworn the HTML docs had a Table of Contents yesterday. Going back to it this morning, I have to flick through each page individually. Am I going mad, or did something change? 😄

**Comment by biapar** [comment]
Hi, there is'nt the menu.

**Comment by daffl** [comment]
I can't reproduce it anymore. Probably a temporary build issue. Try a hard refresh, clearing your cache or opening in incognito mode.

**Comment by leebenson** [comment]
It's working now. Looks like the error was related to this:

<img width="1185" alt="screen shot 2016-11-24 at 15 15 44" src="https://cloud.githubusercontent.com/assets/719722/20603326/eba3bfa4-b258-11e6-9c4f-2e5af2afa350.png">

A few hard refreshes, and we're back...
