### ISSUE TITLE
Common hooks notation

### ISSUE THREAD

**Issue by osenvosem** [feathersjs/feathers-docs#308]
https://docs.feathersjs.com/hooks/common.html

It seems a notation like `remove(fieldName: string, ...fieldNames?: string[]): HookFunc` means that you should pass string and then an optional array of strings. This is confusing and should be changed to something more comprehensible.

**Comment by eddyystop** [comment]
Isn't this correct TypeScript syntax?

**Comment by osenvosem** [comment]
@eddyystop as far as I remember `string[]` means array of strings according the TypeScript syntax.

**Comment by eddyystop** [comment]
I checked TypeScript docs and `...rest: string[]` appears to be commonly used.

Please reopen this if its otherwise.
