### ISSUE TITLE
Visible JavaScript displayed on some documentation pages

### ISSUE THREAD

**Issue by cklmercer** [feathersjs/feathers-docs#312]
I'm seeing this script being displayed on some pages. 
I'm using Google Chrome `Version 54.0.2840.99 m (64-bit)`

It's not being displayed on all pages.
It is being displayed on this page consistently. [https://docs.feathersjs.com/hooks/usage.html#communicating-with-other-services](https://docs.feathersjs.com/hooks/usage.html#communicating-with-other-services)

![image](https://cloud.githubusercontent.com/assets/5618812/20642312/a091ca04-b3d1-11e6-9017-88a2b4c5d1e4.png)

**Comment by daffl** [comment]
This is fixed now. It was one of the plugins setting `display: block` for some script tags.
