### ISSUE TITLE
Wrong package name in docs

### ISSUE THREAD

**Issue by jinwyp** [feathersjs/feathers-docs#322]
https://docs.feathersjs.com/hooks/common.html

ProTip: Hooks previously in feathers-hooks are included with the common hooks. As of v1.6.0, feathers-hooks instead exports **feathers-hooks-common** to provide backward compatibility. feathers-hooks will become part of core in Feathers 3.0 and you will have to import **feathers-hooks-common** separately.

package name "feathers-hooks-common" should be "feathers-common-hooks" .  https://github.com/feathersjs/feathers-hooks-common

when I type npm i feathers-hooks-common get error .

**Comment by eddyystop** [comment]
`feathers-hooks-common` is the repo being used, and so the name in the docs is correct.

I did not experience any problems running `npm i fedathers-hooks-common`.

What error did you get?
What version of node (`node -v`) and npm (`npm -v`) are you running?

**Comment by jinwyp** [comment]
Sorry , I wrote wrong link. 

the wrong text on page https://docs.feathersjs.com/hooks/bundled-deprecated.html 

ProTip: The built-in hooks are being deprecated in favor of Common Hooks. All of these are currently available as part of **feathers-common-hooks**. Please start using that module.

package name "feathers-common-hooks" should be "feathers-hooks-common" .

when I type npm i feathers-common-hooks get error .

**Comment by daffl** [comment]
Closed via #325
