### ISSUE TITLE
Using a view engine: question

### ISSUE THREAD

**Issue by osenvosem** [feathersjs/feathers-docs#328]
I do [as it laid out in the documentation](https://docs.feathersjs.com/guides/using-a-view-engine.html) but it seems it doesn't work properly.
I have configured user service and authentication. All works well with the feathers client. But there is no restrictions when I use a custom route and use my 'messages' service in it, internally.

```js
// hooks for the message service
messageService.before({
  all: [
    authHooks.verifyToken(),
    authHooks.populateUser(),
    authHooks.restrictToAuthenticated(),
    authHooks.queryWithCurrentUser({ idField: '_id', as: 'author' }),
    function testHook(hook) {} // hook being executed during request on custom route
  ]
});
```

```js
// custom route
app.get('/messages', (req, res, next) => {
  console.log(req.feathers); // has provider === rest
  app.service('/api/messages')
    .find()
    .then(messages => { res.render('messages', { messages }); })
    .catch(err => next(err));
});
```
So the custom route has no restrictions. I didn't understand how do I exactly suppose to use view engine with the restrictions. How to properly restrict access to custom routes?

**Comment by marshallswain** [comment]
Hmmm.  You might have to set a provider on the internal queries:

```js
app.service('/api/messages')
    .find({provider: 'rest'})
```

I know that some hooks were setup to skip if they were internal calls.  Those are probably included.  It might actually be better to set `provider: 'internal'` if it works.

**Comment by marshallswain** [comment]
And it that doesn't work, it might be `{params: {provider: 'rest'}}`  I'm a bit rusty.

**Comment by osenvosem** [comment]
@marshallswain the service gets `params` object, so `.find({ provider: 'rest' })` seems to be the right way to assign provider value. But when I'm doing this I'm always getting `NotAuthenticated: Authentication token missing.` with correct token in the `Authorization` header.

**Comment by daffl** [comment]
I think @ekryski can elaborate how to do this with auth 1.0-beta. You need to enabled authentication via cookies and then us it [in server side rendering](https://github.com/feathersjs/feathers-authentication/blob/master/docs/new-1.0-features.md#server-side-rendering) with the [authenticate Express middleware](https://github.com/feathersjs/feathers-authentication/blob/master/src/express/authenticate.js).

**Comment by osenvosem** [comment]
@daffl it would be fine to have a tutorial how to deal with authentication/authorization when one renders React/view engine on the server side.

**Comment by ekryski** [comment]
Ok. Let's slow down a second. @osenvosem what are you trying to do? It seems that your question is about why your internal call to `app.service('/api/messages').find()`. This is because you are calling it without a provider and all of the old auth hooks only run if `hook.params.provider` is set.

@marshallswain was almost right. In order to ensure your hooks run you'd need to call it like this:

```
app.service('/api/messages').find({}, {provider: 'rest'})
```

Using the old auth if you want your `/messages` route to be restricted you'll need to lock that down yourself with middleware and you should just call your `/api/messages` service internally without passing params (because you should have already loaded authenticated the user and loaded them.

---

Guides for doing this stuff with the new auth 1.0 will come in due time.

**Comment by osenvosem** [comment]
@ekryski I was trying to restrict access to a server rendered endpoint.
As far as I know the `.find()` method is supposed to receive just one `params` object which has `provider` property on it, not two.
Whatever, thanks for the answers, I think I should dig 1.0 version. Do you have documentation for it besides the [readme](https://github.com/feathersjs/feathers-authentication) and [Migrating guide](https://github.com/feathersjs/feathers-authentication/blob/master/docs/migrating.md)?
