### ISSUE TITLE
Dead link in hooks usage page.

### ISSUE THREAD

**Issue by roelvan** [feathersjs/feathers-docs#330]
The `soft delete example` link.

**Comment by daffl** [comment]
It's probably https://docs.feathersjs.com/hooks/common.html#softdelete now

**Comment by eddyystop** [comment]
You can switch to the Auk version of the docs using the dropdown in the
left column of the Featherjs GitBook. The hook documentation there is up to
date and all the hooks are in `feathers-hooks-common` already.

**Comment by roelvan** [comment]
Ok thanks, will do!
