### ISSUE TITLE
Get logo into the left side menu

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-docs#35]
It would be nice to see the logo + text instead of the "The FeathersJS book" text:

<img width="689" alt="screen shot 2016-02-21 at 11 00 04 pm" src="https://cloud.githubusercontent.com/assets/338316/13211636/e6c07bce-d8ee-11e5-969b-39f92771c5b2.png">

**Comment by ekryski** [comment]
I'm not sure if you can. I had quickly looked into it but we can keep this open to see if we can find a way.

**Comment by daffl** [comment]
Fixed!
