### ISSUE TITLE
question - angular2 - documentation where should i place the files?

### ISSUE THREAD

**Issue by david-gang** [feathersjs/feathers-docs#350]
Hi all,

I read the documentation https://docs.feathersjs.com/frameworks/angular2.html but it is not clear to me where to put the files?  For example Where is the place to put the file feathers.service.ts?

Additionally as angular2 is heavyweight it would be nicer to seperate it from the package.json of feathers. Otherwise it would be confusing which dependency is because of feathers and which due to angular . 
More important, people will use the angular-cli, so we will have to seperate somehow the directories so that angular-cli and the feathers-cli would not disturb one to another.
How is it doable?

For example this is a nice example of how to part the code with express:
https://github.com/vladotesanovic/angular2-express-starter
The server code is in the server folder. The client code is in the src directory.
Would you recommend such an approach? If yes, what do i have to configure that it will work?

Thanks,
David

**Comment by daffl** [comment]
I'm going to close this since we removed the framework guides from the documentation. We will probably turn them into blog posts but still need someone to volunteer for doing so for Angular 2.
