### ISSUE TITLE
How to get friends info after user log in with Linkedin successfully?

### ISSUE THREAD

**Issue by henrykapostel** [feathersjs/feathers-docs#352]
Hello,

I have done successfully login/signup with Linkedin and am going to try to invite user's friend of Linkedin. So I need friends information from user's Linkedin info.
Is there any way to get these(for example, friends information - name, avatarurl, phone number,...) when the user login/signup with Linkedin?

I am trying to find out the solution but there isn't anything.
Please help me.

Here is my some code and please check it out.

"linkedin": {
      "provider":"linkedin",
      "endPoint":"/auth/linkedin",
      "clientID": "...",
      "clientSecret": "...",
      "permissions": {
        "scope": ["r_basicprofile", "r_emailaddress"]
      },
      "profileFields": ["id", "email-address", "first-name", "last-name", "formatted-name", "picture-url"]
    }

**Comment by daffl** [comment]
Once a user authenticated with Linkedin you will get an oAuth access token and then use the [node-linkedin](https://www.npmjs.com/package/node-linkedin) module to make requests to the LinkedIn API:

```js
var Linkedin = require('node-linkedin')('app-id', 'secret', 'callback');
var linkedin = Linkedin.init('my_access_token');
```

**Comment by henrykapostel** [comment]
Thanks for your solution.
I have got another problem, and how to invite the friend of facebook to the app?
I think this is same as before but I couldn't found the correct node module of facebook.
Could you let me know about this?

**Comment by daffl** [comment]
I think invites are a Facebook feature right? Did you have a look at the official [Facebook Node module](https://www.npmjs.com/package/fb)

**Comment by marshallswain** [comment]
I'm closing this issue since the remaining question is similar to the first and can be solved in the module that @daffl provided.  Please reopen if you feel like I've missed something.
