### ISSUE TITLE
Authentication recipes page.

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-docs#363]
We need a page where people can link to gists of their auth setup.

Here's a great example by @Ivykp that uses the FacebookToken strategy: https://gist.github.com/Ivykp/1c91293b7c8f52306c536f615096e778

**Comment by eddyystop** [comment]
I think we need an intro for each gist.

- The problem being solved.
- Short outline of how its being solved.
- Notes, including restrictions, things to watch out for, etc.

**Comment by marshallswain** [comment]
@ekryski says he has some guide-like articles, so we'll be open to having a mix of guides and gists.  +1 on keeping them in the feathersjs group.

**Comment by ekryski** [comment]
Duplicate of #452. The linked gist is now out of date.
