### ISSUE TITLE
Replace tagline ?

### ISSUE THREAD

**Issue by bertho-zero** [feathersjs/feathers-docs#396]
Hi,

Do you intend to replace the current tagline which is `A minimalist real-time framework for tomorrow's apps.` by `A REST and realtime API layer for modern applications.` in the documentation ?

**Comment by daffl** [comment]
Yes. There is extensive work being done on the documentation in the [auk-reorg branch](https://github.com/feathersjs/feathers-docs/tree/auk-reorg) with many changes in flight. Once that is merged we will make sure that everything is consistent (but will definitely need help reviewing all the new content).
