### ISSUE TITLE
Can you make PRs and squash commits?

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-docs#4]
It seems like GitBook is creating a lot of commits (~360 so far). They do support branches (and PRs?). Maybe @marshallswain knows if they also allow to squash your commits?

**Comment by marshallswain** [comment]
From what I can tell, their editor doesn't support squashing at the moment.

**Comment by marshallswain** [comment]
We could always do that outside the editor when we're ready to merge a branch.

**Comment by daffl** [comment]
Since we had a bunch of merge conflicts we will only do PRs from now and only use the web UI for reviewing and fine-tuning if necessary.
