### ISSUE TITLE
db_dialect undefined

### ISSUE THREAD

**Issue by mmucklo** [feathersjs/feathers-docs#404]
The docs on the Sequelize migration setup refer to a key called "db_dialect".

```javascript
const app = require('../../src/app');
const env = process.env.NODE_ENV || 'development';

module.exports = {
  [env]: {
    url: app.get('db_url'),
    dialect: app.get('db_dialect'),
    migrationStorageTableName: '_migrations'
  }
};
```

When I run things as documented I get the following:

```
root@7fd93358ce33:/opt/api# sequelize db:migrate

Sequelize [Node: 6.9.5, CLI: 2.5.1, ORM: 3.30.2]

Loaded configuration file "migrations/config/config.js".
Using environment "development".
Error: The dialect undefined is not supported. Supported dialects: mariadb, mssql, mysql, postgres, and sqlite.
```

I ended up adding a key in my default.conf for the db_dialect and then it worked.  I also changed the db_url key to the actual key name of the DB url that I have in default.conf (postgres).

Things worked afterwards - just wondering if I'm doing it right?

**Comment by daffl** [comment]
Sounds about right. Can you update the document accordingly in a pull request?
