### ISSUE TITLE
Document the client API

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-docs#422]
We currently have two ways of using Feathers on the client.  
- feathers-client
- individual packages

I think it would simplify communication quite a bit if we used `feathers-client` for all of the examples, and explain only once that they can use separate packages if they want to.  This means all client examples would use `feathers-client`.  This should work well since @daffl moved `feathers-authentication-client` back into the latest `feathers-client`.  Any thoughts or objections before I start doing this?

![screen shot 2017-03-15 at 10 00 42 am](https://cloud.githubusercontent.com/assets/128857/23957958/4d7e9604-0966-11e7-8bbc-351460c78bed.jpg)

**Comment by daffl** [comment]
I have some client docs already (might have to push them though).

I think we should use the module loader / Node examples everywhere and show how to use `feathers-client` in the "Client" chapter.

**Comment by daffl** [comment]
Most of it has been added now in https://docs.feathersjs.com/v/auk-reorg/api/client.html, just need to fill in the remaining blanks.

**Comment by marshallswain** [comment]
I filled in the remaining placeholders in the client docs: https://docs.feathersjs.com/v/auk/api/client.html#feathers-client

**Comment by marshallswain** [comment]
I filled in the remaining placeholders in the client docs: https://docs.feathersjs.com/v/auk/api/client.html#feathers-client

**Comment by daffl** [comment]
Looks like there is still some blanks to fill no?

**Comment by marshallswain** [comment]
I don't see any.  What am I missing?  Maybe Gitbook just hadn't finished building, yet?

**Comment by daffl** [comment]
Yep you're right, hadn't been updated.
