### ISSUE TITLE
Add Common Hooks docs

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-docs#425]
The Common Hooks page is still empty.  I assume this is `feathers-hooks-common`.  @eddyystop Is this complete in another branch?

![screen shot 2017-03-17 at 11 59 00 pm](https://cloud.githubusercontent.com/assets/128857/24069443/cc96d042-0b6d-11e7-84ab-032ca9082e5c.jpg)

**Comment by eddyystop** [comment]
ekryski wanted to move the existing docs and make some changes in format.

**Comment by ekryski** [comment]
I'm on it!

**Comment by ekryski** [comment]
@marshallswain was this an accidental close?

**Comment by marshallswain** [comment]
Do we need something different than what's here: https://docs.feathersjs.com/v/auk/api/hooks-common.html?

**Comment by ekryski** [comment]
Nope I had just missed this PR: https://github.com/feathersjs/feathers-docs/pull/445.
