### ISSUE TITLE
React Native Docs

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-docs#426]
There are a few React Native examples in the old docs that haven't made it into the new, as fas as I'm aware.  Where do we want them to go?  

https://docs.feathersjs.com/clients/rest.html#react-native-usage
https://docs.feathersjs.com/clients/socket-io.html#react-native-usage
https://docs.feathersjs.com/clients/primus.html#react-native-usage

**Comment by daffl** [comment]
I have a bunch of client docs I'll push shortly here.

**Comment by ekryski** [comment]
Related https://github.com/feathersjs/feathers-docs/pull/438

**Comment by daffl** [comment]
Most of these have been added in #438
