### ISSUE TITLE
FAQ Blog Post: Why do I get the wrong HTTP error code?

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-docs#433]

**Comment by ekryski** [comment]
This section in the docs is empty. https://docs.feathersjs.com/faq/readme.html#i-am-not-getting-the-right-http-error-code

@marshallswain @daffl should we remove it or was their supposed to be content there? I don't remember this being all that common a question but I could be wrong.

Let me know what we need to do here.

**Comment by marshallswain** [comment]
I thought there used to be content in the old version.

**Comment by ekryski** [comment]
yes, there is. k I'll add it in right now.

**Comment by ekryski** [comment]
k fixed now so it's not just blank.

**Comment by daffl** [comment]
That was intentional because the answer should work for both of those FAQs but this change makes sense to make that more clear.

**Comment by ekryski** [comment]
Ya I realized what you were doing when I looked at the source but the way the formatting came out in HTML format made it look like it was just incomplete.
