### ISSUE TITLE
Rename Providers to Transports

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-docs#437]
@feathersjs/core-team what do y'all think about renaming Providers to Transports everywhere in the docs?  I think it's a more accurate name, and it's easier to grasp what they do.

**Comment by eddyystop** [comment]
+1 as `transport` is more obvious.

However is too late to do that? We'd at least have to keep both `provider` and `transport` for some time.

**Comment by marshallswain** [comment]
I don't think we'd need to wait, as it's the topic that you need to know the least about to use Feathers.  We can just put a note somewhere.

**Comment by eddyystop** [comment]
If it changes, I would suggest leaving `provider` for a while. That would
be quite the breaking change.

On Sat, Mar 18, 2017 at 9:54 AM, Marshall Thompson <notifications@github.com

**Comment by omeid** [comment]
So much churn guys!

There is little meaning that can be inferred from `provider` or `transport` without reading the documentation, and once you read the documentation there is little difference between `transport` or `provider` as you can read both of them as short for `transport provider`.

It would be nice if more focused was put on wrapping up the forever waiting `Auk` release before tackling new ideas.

:)

**Comment by marshallswain** [comment]
@omeid, this is a tiny change with almost no impact to the workload.  The only way we can get more focus on wrapping up the Auk release would be for more community members to volunteer and dive in.  We are doing our best, and probably got a little too ambitious for the Auk release with this project we build in our spare time.

**Comment by omeid** [comment]
Sure, but it is still work and there is many external blog posts and tutorials that will become confusing.

**Comment by bitsoflogic** [comment]
I'm new to the community, having just recently found Feathers.  Both terms are vague, but they offer different implications. At first, I was indifferent and actually preferred the term `adapter` that the Ember.js community uses for their connection types.  Thinking it through, I expect different things from each (with no formal research):

- provider: something that'll return data, probably after some manipulation or io
- transport: the vehicle data uses to get from one place to another
- adapter: something that sends/recieves data and changes it into a common form

I don't know enough of the internals of Feathers yet to have an opinion between `transport` and `adapter`, but either way it seems to add some clarity.  Might be good to see what the other communities like Angular and React are calling them as well. Consistency wins. 

I also agree this should be treated as a major change.

**Comment by marshallswain** [comment]
@bitsoflogic 

> transport: the vehicle data uses to get from one place to another

This is exactly what "providers" are.

> I also agree this should be treated as a major change.

Ok.  I'll be nicer.  ;)

**Comment by ekryski** [comment]
@marshallswain I agree and think we should :shipit: into the Auk docs. Those docs are a major change so it would be a good time to do it.

**Comment by ekryski** [comment]
catching up on commits/PRs to the new Auk docs branches, this is happening! 🎉 

Going to close again.
