### ISSUE TITLE
Categorize the common hooks

### ISSUE THREAD

**Issue by bertho-zero** [feathersjs/feathers-docs#450]
Hi,
why do not you categorize the hooks for the auk version in the sidebar? I found it more convenient for find out.

https://docs.feathersjs.com/v/auk/api/hooks-common.html

In the previous version:
- Altering Data
- Query Params
- Database
- Validation
- Utilities
- Running hooks conditionally
- Utilities for Writing Hooks

**Comment by eddyystop** [comment]
The categorization was subjective. Some hooks could validly be in Database or Utilities. It also make it awkward to find the docs for a hook when you knew its name.

We've debated this and decided that alphabetical order was preferred.

We also refer to one hook's related hooks in the docs, e.g. "See also dePopulate, serialize." for populate. This gives the most important information that the Catgeories provided.

**Comment by marshallswain** [comment]
I wouldn't mind seeing the categories at the top of the page, if we want to consider that.  But I find them much easier to access alphabetically in the sidebar.
