### ISSUE TITLE
Search on docs doesn't work

### ISSUE THREAD

**Issue by ellipticaldoor** [feathersjs/feathers-docs#455]
Now when I enter to https://docs.feathersjs.com/ ant try to search on the top left corner I get I transparent white screen over the page an no result appears.

**Comment by marshallswain** [comment]
This is due the way search is implemented at Gitbook.  It uses large index files that have to be transferred before it can show results.  It's client side lunr search.  I have noticed this issue a few times.  It usually clears up for me after a while.  Do you have the same problem if you switch to the Auk docs?

**Comment by ellipticaldoor** [comment]
There is an url for the auk docs?

**Comment by marshallswain** [comment]
There's a dropdown in every docs page above the Feathers logo in the sidebar.

**Comment by ellipticaldoor** [comment]
Now goes perfect in both now, you are right it clears up after a while.
