### ISSUE TITLE
Testing Guides

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-docs#460]
This is the first one: https://github.com/feathersjs/feathers-hooks/issues/146

**Comment by daffl** [comment]
We also have https://docs.feathersjs.com/testing/readme.html

I've been debating if we make testing part of the chat guide but I think it would make for a better blog post?

**Comment by marshallswain** [comment]
Definitely a blog post.  We can link to it at the end of the chat guide, next to the link to the frameworks page.

**Comment by eddyystop** [comment]
I added a short page on testing hooks in the Basic Guide when its info on hooks was being expanded.  https://docs.feathersjs.com/guides/step-by-step/basic-feathers/testing-hooks.html
