### ISSUE TITLE
Docs version switcher problems

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-docs#476]
The version switcher allows you to switch to the Auk version, but you can't go back to master.

**Comment by daffl** [comment]
I think that's a bug in the plugin. It doesn't update the dropdown to the value you selected. We'll probably have make a fork with a fix (which shouldn't be too hard).

**Comment by ekryski** [comment]
ok I've fixed this by creating our own plugin and switching over to that. https://github.com/feathersjs/gitbook-plugin-feathers-versions
