### ISSUE TITLE
Outline and progress

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-docs#5]
Here is the current outline for the documentation:

* [Getting Started](getting-started/readme.md)
   * [Quick Start](getting-started/quick-start.md)
   * [Your First App](getting-started/your-first-app/readme.md)
* [Why Feathers](why/readme.md)
   * [Express + Socket.io](why/express-socketio.md)
   * [Feathers vs Meteor](why/meteor.md)
   * [Feathers vs Sails](why/sails.md)
   * [Feathers vs Firebase](why/firebase.md)
* [Services](services/readme.md)
* [REST](rest/readme.md)
* [Real-Time](real-time/readme.md)
   * [Service events](real-time/events.md)
   * [Socket.io](real-time/socket-io.md)
   * [Primus](real-time/primus.md)
   * [Event Filtering](real-time/filtering.md)
* [Client Use](clients/readme.md)
   * [Universal Feathers](clients/feathers.md)
   * [REST](clients/rest.md)
   * [Socket.io](clients/socket-io.md)
   * [Primus](clients/primus.md)
* [Databases](databases/readme.md)
   * [Pagination and sorting](databases/pagination.md)
   * [Querying](databases/querying.md)
   * [Extending adapters](databases/extending.md)
   * [In Memory](databases/memory.md)
   * [NeDB](databases/nedb.md)
   * [Mongoose](databases/mongoose.md)
   * [Sequelize](databases/sequelize.md)
   * [KnexJS](databases/knexjs.md)
   * [Waterline](databases/waterline.md)
* [Hooks](hooks/readme.md)
   * [Bundled hooks](hooks/bundled.md)
* [Middleware](middleware/readme.md)
   * [Express Middleware](middleware/express.md)
   * [Routing and Versioning](middleware/routing.md)
* [Authentication](authentication/readme.md)
   * [Local (username & password)](authentication/local.md)
   * OAuth (Twitter, Facebook, etc)
   * Two-Factor (MFA)
* [Authorization / Access Control](authorization/readme.md)
   * [Bundled Auth Hooks](authorization/bundled-hooks.md)
* [API](api/readme.md)
* [Guides](guides/readme.md)
   * Migrating to Feathers 2
   * Creating a plugin
   * React and React Native
   * CanJS
* [Help](help/readme.md)
   * [FAQ](help/faq.md)
   * [Contributing](contributing.md)
   * [Changelog](changelog.md)
* [License](license.md)

/cc @marshallswain @ekryski and anybody else for thoughts

**Comment by marshallswain** [comment]
This layout makes much more sense.

Do we want an Examples section, I'd say toward the end, for things like the [feathers-react-native-chat](https://github.com/feathersjs/feathers-react-native-chat)  Actually, weren't we planning some npm integration with the site that crawls the feathers-plugin tag?

Is there a provider spec that we could show somewhere so users could build more providers?

How about the plugin docs?  Where would, say, feathers-configuration docs go?  Stay in the README?  Maybe an official plugins section.

What are the thoughts on the Microservices section and the Performances sections that were removed?

**Comment by ekryski** [comment]
I don't want the `guides` part to be a dumping ground but I think that a lot of what you mentioned @marshallswain could maybe go in there for now?? We might need an examples section later though.

I do think we probably need a plugins section.

**Comment by daffl** [comment]
I'd like to make a plugin guide but I don't think anybody will create their own provider any time soon (maybe as feature requests but then we can always create a guide later).

I think the guides can for now be a dumping ground for things that aren't fully fleshed out yet and client framework specific guides (so it doesn't look like Framework X isn't supported, we just don't have a guide for it). I'd also include the React Native Chat there in the "React and React Native" guide and maybe a page for examples (if we have enough?) and an overview of incubating plugins (like feathers-batch or feathers-sync) with a short description and a link to their repository.

We should keep track of questions and topics that come up more often and turn them into top level topics when there is enough solid content and interest.

**Comment by daffl** [comment]
Here is my current progress of chapters that I wrote and reviewed (which means they definitely have to be reviewed by someone else ;):

* [ ] [Getting Started](getting-started/readme.md)
   * [ ] [Quick Start](getting-started/quick-start.md)
   * [ ] [Your First App](getting-started/your-first-app/readme.md)
* [ ] [Why Feathers](why/readme.md)
   * [ ] [Express + Socket.io](why/express-socketio.md)
   * [ ] [Feathers vs Meteor](why/meteor.md)
   * [ ] [Feathers vs Sails](why/sails.md)
   * [ ] [Feathers vs Firebase](why/firebase.md)
* [ ] [Services](services/readme.md)
* [ ] [REST](rest/readme.md)
* [ ] [Real-Time](real-time/readme.md)
   * [ ] [Service events](real-time/events.md)
   * [ ] [Socket.io](real-time/socket-io.md)
   * [ ] [Primus](real-time/primus.md)
   * [ ] [Event Filtering](real-time/filtering.md)
* [ ] [Client Use](clients/readme.md)
   * [ ] [Universal Feathers](clients/feathers.md)
   * [ ] [REST](clients/rest.md)
   * [ ] [Socket.io](clients/socket-io.md)
   * [ ] [Primus](clients/primus.md)
* [ ] [Databases](databases/readme.md)
   * [ ] [Pagination and sorting](databases/pagination.md)
   * [ ] [Querying](databases/querying.md)
   * [ ] [Extending adapters](databases/extending.md)
   * [ ] [In Memory](databases/memory.md)
   * [ ] [NeDB](databases/nedb.md)
   * [ ] [Mongoose](databases/mongoose.md)
   * [ ] [Sequelize](databases/sequelize.md)
   * [ ] [KnexJS](databases/knexjs.md)
   * [ ] [Waterline](databases/waterline.md)
* [ ] [Hooks](hooks/readme.md)
   * [ ] [Bundled hooks](hooks/bundled.md)
* [ ] [Middleware](middleware/readme.md)
   * [ ] [Express Middleware](middleware/express.md)
   * [ ] [Routing and Versioning](middleware/routing.md)
* [ ] [Authentication](authentication/readme.md)
   * [ ] [Local (username & password)](authentication/local.md)
   * [ ] OAuth (Twitter, Facebook, etc)
   * [ ] Two-Factor (MFA)
* [ ] [Authorization / Access Control](authorization/readme.md)
   * [ ] [Bundled Auth Hooks](authorization/bundled-hooks.md)
* [ ] [API](api/readme.md)
* [ ] [Guides](guides/readme.md)
   * [ ] Migrating to Feathers 2
   * [ ] Creating a plugin
   * [ ] React and React Native
   * [ ] CanJS
* [ ] [Help](help/readme.md)
   * [ ] [FAQ](help/faq.md)
   * [ ] [Contributing](contributing.md)
   * [ ] [Changelog](changelog.md)
* [ ] [License](license.md)

**Comment by ekryski** [comment]
I just wrapped up the last core piece. I think we can probably close this issue now and create separate issues for each guide.

Wahoo nice work @marshallswain and @daffl! :tada: :beers:

**Comment by daffl** [comment]
Awesome.
