### ISSUE TITLE
i wanna translate in my gitbook about feathers-docs contents

### ISSUE THREAD

**Issue by Lutece** [feathersjs/feathers-docs#546]
May I create a gitbook by translating feathers-docs contents? 
I tried to explain the Nuxt.js - Feathers.js stack to the Koreans, 
so Nuxt.js was translated and Feathers.js was not translated.

**Comment by marshallswain** [comment]
I think we could probably set you up a repo for the Korean translation and add it to our CI & deployment.  @feathersjs/core-team what are your thoughts?

**Comment by daffl** [comment]
We started a discussion in #545 but @Lutece closed it (why I am not sure).

**Comment by Lutece** [comment]
@daffl Sorry! I think my idea of ​​an issue is that I need to create an feathers.js api cheat sheet personally, my bad :(

**Comment by Lutece** [comment]
@marshallswain I will do my best! :)

@marshallswain @daffl 
thank you! and have a happy day all :)

**Comment by Lutece** [comment]
I will start to translate some contents in feathers-docs.! :)

**Comment by daffl** [comment]
No, sorry, we have been thinking about creating a cheat sheet (and some overviews) for a while now. I am just not sure how it should look like though.

**Comment by Lutece** [comment]
@daffl okay, I will wait 👍

**Comment by ekryski** [comment]
Closing this in favour of tracking discussion in #545
