### ISSUE TITLE
Feathers + Angular 2

### ISSUE THREAD

**Issue by yberstad** [feathersjs/feathers-docs#55]
Hi!

I'm trying to get up and running with the Feathers. I'm therefore trying out the Feathers + Angular 2 guide from the http://docs.feathersjs.com/guides/angular2.html. I have completed the Angular2 walkthrough, and I have gone through all the Feathers steps. But when I'm trying run it with npm start, I get the following error:

    services/feathers.service.ts(1,18): error TS2304: Cannot find name 'require'.

The line it is referring to is this:

    const feathers = require('feathers/client');

Under the Typescript section, from the guide, it states, *You'll also need a module loader, a commonly used one is Webpack. If you've gone through the Angular 2 quickstart you should be good to go.*

The Angular 2 quickstart used SystemJS, I have tried to figure out how to configure it to make it work, but with no luck.

Sorry for not figuring this out, but I coming from C# background, and I'm struggling a bit with all the different syntax variations of ES5 vs ES6 vs Typescript and transpiling... 

Thanks in advance!

**Comment by ekryski** [comment]
Maybe @harangue can weigh in here. He wrote the guide for us and unfortunately, I don't know much about typescript or Angular2 so I'm not going to be much help here.

**Comment by harangue** [comment]
Hey @yberstad! Sorry for the delayed response. If you look at [this SO](http://stackoverflow.com/questions/31173738/typescript-getting-error-ts2304-cannot-find-name-require) issue I think you'll find the solution to your problem.

**Comment by ekryski** [comment]
@yberstad let us know if that doesn't work and we can reopen. I'm going to close this.

**Comment by yberstad** [comment]
@harangue Thank you so much for you help, it works now! :)
