### ISSUE TITLE
Step-Generators-Auth Bad Link

### ISSUE THREAD

**Issue by iabw** [feathersjs/feathers-docs#556]
The "guides" link in the ["What's Next?"](https://docs.feathersjs.com/guides/step-by-step/generators/gen-authentication.html#whats-next) section of the guide to adding authentication via generator is bad.

It currently points at https://docs.feathersjs.com/guides/authentication/readme.md

Looks like that's supposed to be https://docs.feathersjs.com/guides/auth/readme.html

**Comment by daffl** [comment]
Closed via #557
