### ISSUE TITLE
Comment:Step-Generators-Readme

### ISSUE THREAD

**Issue by MVSICA-FICTA** [feathersjs/feathers-docs#560]
Hi Features, thanks for the new Auk release! Just browsing the docs and noticed the folder structure being generated for a Features only app. Saw some article a ways back that looked like it had two apps in it, a Vue app and a Features app. The integration did not look to seamless on the surface at the time. I'm particular about project structure and It would be helpful to get a detailed rundown on how to best integrate Vue and Features under one unified project.

**Comment by eddyystop** [comment]
I recommend you start by checking out Feathers' #vue channel on Slack. https://feathersjs.slack.com/messages/C11VCU0Q4/ . The people there are all using Vue in production.

**Comment by daffl** [comment]
Also, @marshallswain made a great example for the [chat application using Vuex](https://github.com/feathersjs/feathers-chat-vuex).

**Comment by MVSICA-FICTA** [comment]
Thanks, glad to learn about the #vue channel and the example 💯
