### ISSUE TITLE
Comment:Chat-Processing

### ISSUE THREAD

**Issue by OxaD** [feathersjs/feathers-docs#562]
Not an issue, but an information to add in the instructions: https://docs.feathersjs.com/guides/chat/processing.html

Before restarting the server, we have to delete previous created messages from the messages.db file. Otherwise, because of messages without "userId" we got the following error in the developer tools console:

Uncaught (in promise) BadRequest {type: "FeathersError", name: "BadRequest", message: "ParentField userId for user depth 1 is undefined. (populate)", code: 400, className: "bad-request"…}

**Comment by marshallswain** [comment]
@OxaD would you care to hit the "edit this page" link at the top of [this page](https://docs.feathersjs.com/guides/chat/processing.html#) and write these edits where you think they should go?  Thanks!
