### ISSUE TITLE
Comment:Chat-Processing

### ISSUE THREAD

**Issue by firewater** [feathersjs/feathers-docs#565]
Excellent work so far, guys. Keep forging ahead!

I'm following the Chat App tutorial and encountered some confusion about what exactly is going on in the  "Populating the message sender" section. So I was wondering if someone could make a quick revision so that the section is a little easier to understand from a newbie's perspective.

I know you guys have bigger fish to fry so thanks for considering this doc revision.

**Comment by marshallswain** [comment]
Thanks @firewater.  I added another sentence to help make it more clear what the goal is.  I also added a link to the `populate` hook docs so the reader can learn more about how it works.  https://github.com/feathersjs/feathers-docs/commit/f4d059f1433c985a125afff86fddfcd640d39762
