### ISSUE TITLE
Wrong name in the generator image

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-docs#57]
verify should be restrict-to-sender, I believe.

![screen shot 2016-03-16 at 1 20 35 am](https://cloud.githubusercontent.com/assets/128857/13804785/65b82a20-eb15-11e5-8250-77f767115d22.jpg)

**Comment by ekryski** [comment]
LOL. Nice hack @daffl. It's so that he didn't have to make a new screenshot because we were in a rush and I'm stubborn.

**Comment by daffl** [comment]
Yeah, I removed it in https://github.com/feathersjs/feathers-docs/commit/94333aed64263c0a2cecfca2c53bf7f03c5204b9. I think that's fine since we already show a hook generator screen before that anyway.
