### ISSUE TITLE
Comment:Step-Basic-Hooks-2

### ISSUE THREAD

**Issue by ElliotPsyIT** [feathersjs/feathers-docs#576]
Comment:Step-Basic-Hooks-2 -- I've been following the docs guide getting up to speed on feathersjs.  All has gone well until reaching the `softDelete` hook, where the userService `before` hook failed.  See below.  I double checked that I'm using the correct server side and client side code.  

I'm a newbie and I certainly could have missed something simple or done something wrong.

Any assistance would be appreciated!
 
```
userService.before({
    all: when(hook => hook.method !== 'find', softDelete()),
```
Error in the browser console (tried running multiple times):

```
created Jane Doe item
 Object
feathers-app-del.js:13 created John Doe item
 Object
feathers-app-del.js:14 created Judy Doe item
 Object
feathers-app-del.js:15 created Jack Doe item
 Object
http://localhost:3030/users/58cn9iAyCv1tMPcq Failed to load resource: the server responded with a status of 500 (Internal Server Error)
feathers-app-del.js:26 Error occurred: Error: Cannot read property 'get' of undefined
    at GeneralError.ExtendableBuiltin (unpkg.com/feathers-client@1.9.0/dist/feathers.js:1545)
    at GeneralError.FeathersError (unpkg.com/feathers-client@1.9.0/dist/feathers.js:1620)
    at new GeneralError (unpkg.com/feathers-client@1.9.0/dist/feathers.js:1805)
    at convert (unpkg.com/feathers-client@1.9.0/dist/feathers.js:1889)
    at toError (unpkg.com/feathers-client@1.9.0/dist/feathers.js:3270)
```

**Comment by eddyystop** [comment]
That example not longer runs because of https://github.com/feathersjs/feathers-hooks-common/issues/147 .  The issue mentions its been fixed and it'll be published by Monday.

Once the guide is at v2.2.0 (see package.json) you'll have to make a new fork to have the latest dependencies.

**Comment by ElliotPsyIT** [comment]
Ah, very good.  I'm a newbie and kept thinking it was me.  I'll have a look at the issue to learn more, and re-fork after the fix.  Much appreciated.

**Comment by wszgxa** [comment]
just change the doc's `feathers-hooks-common` to 3.5.0.

**Comment by eddyystop** [comment]
Fixed in https://github.com/feathersjs/feathers-docs/pull/633
