### ISSUE TITLE
Comment:Step-Basic-Db-connector

### ISSUE THREAD

**Issue by Jairos2015** [feathersjs/feathers-docs#579]
Comment:Step-Basic-Db-connector >> A doubt: The code in the example is different, in parts to that of the guide. What is the most recent code?. Thank you.

Excuse me I found the differences. You have already taken them into account.
http://htmlpreview.github.io/?https://github.com/feathersjs/feathers-docs/blob/master/examples/step/_diff/01-rest-1-side.html

**Comment by eddyystop** [comment]
Np.
