### ISSUE TITLE
Comment:Step-Basic-Rest-api-server

### ISSUE THREAD

**Issue by maarteNNNN** [feathersjs/feathers-docs#583]
Comment:Step-Basic-Rest-api-server
A typo in the docs, 2x : at jane.doe.

> GET all users
[
 {"email":"judy.doe@gmail.com","password":"7jHw","role":"user","_id":"pvcmh9X2i9VZgqWJ"},
 {"email"**::**"jane.doe@gmail.com","password":"X2y6","role":"admin","_id":"sbkXV7LVkMhx1NyY"},
 {"email":"john.doe@gmail.com","password":"i6He","role":"user","_id":"uKhqOp4R4hABw9oO"}
]

I purposed changes here:
https://github.com/feathersjs/feathers-docs/compare/master...maarteNNNN:patch-1

I'm sorry if I'm doing it the wrong way I'm kinda new to Git and Github.

**Comment by eddyystop** [comment]
Thanks. Merged.

**Comment by eddyystop** [comment]
It takes a while to get used to GitHub. Then you forget what the fuss was about.

The best way to submit a PR is https://help.github.com/articles/creating-a-pull-request-from-a-fork/

Thanks again.

**Comment by maarteNNNN** [comment]
I'm glad I could help in a minor way and thank you for the refence I'll try to do it better next time!

**Comment by eddyystop** [comment]
Here's a more detailed guide for PRs that I put together a while ago. https://github.com/eddyystop/feathers-reduxify-authentication/blob/master/CONTRIBUTING.md
