### ISSUE TITLE
Comment:Step-Generators-Hook

### ISSUE THREAD

**Issue by MatthijsMali** [feathersjs/feathers-docs#593]
Comment:Step-Generators-Hook

The generator did not ask me for a method to use. So it was not completely wired into the app.

**Comment by eddyystop** [comment]
That would be strange. Could you provide a screen shot of such a dialogue?

**Comment by MatthijsMali** [comment]
<img width="421" alt="screen shot 2017-05-08 at 14 47 23" src="https://cloud.githubusercontent.com/assets/2405206/25804779/5c1e693e-33fd-11e7-9214-d15f37b0a31c.png">

**Comment by marshallswain** [comment]
Can you try again after npm install -g feathers-cli@latest

**Comment by MatthijsMali** [comment]
I've been doing a few test projects with Feathers. I tried the command again, and it works fine now. Unfortunately I do not have the testproject where the issue occurred anymore.

It happened to my while following this step in the tutorial: https://docs.feathersjs.com/guides/step-by-step/generators/gen-hook.html

Unfortunately I do not have time right now to go through the process again.

**Comment by eddyystop** [comment]
Closing this as there's been no reply for over a month.
