### ISSUE TITLE
Create a guide for social sign-in

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-docs#60]
This guide might cover:
- How to setup an app (maybe show Facebook or Google)
- How to use OAuth2 with Feathers
- How to cherry pick properties from a user's social profile
- How to consolidate user's accounts

**Comment by jay-depot** [comment]
I just happen to be trying to figure out how to do these things for a project, myself. I'd love to help compile all the info into a guide if I could get a few pointers on where to look.

**Comment by ekryski** [comment]
Duplicate of #452
