### ISSUE TITLE
Comment:Step-Basic-Readme

### ISSUE THREAD

**Issue by georgehorrell** [feathersjs/feathers-docs#602]
Comment:Step-Basic-Readme

There's nothing here?

**Comment by eddyystop** [comment]
The page has: "Let's write some Feathers code because, once we understand that, Feathers generators will be straight forward."

After the introduction to Feathers, and the installation of the examples, this let's the reader know what we will be doing next and why.

Or am I missing something here?

**Comment by eddyystop** [comment]
Let me know if I can close this or not.

**Comment by marshallswain** [comment]
I added a line to clarify that we start writing code on the next page.
