### ISSUE TITLE
Comment:Step-Basic-Real-time

### ISSUE THREAD

**Issue by EnFinlay** [feathersjs/feathers-docs#603]
Comment:Step-Basic-Real-time

The code snippet 

```
users.filter((data, connection) => {
  delete data.password;
  return connection.user ? data : false;
});
```

Seems to be intended for the client side, since the server side code doesn't declare the `user` variable anywhere (https://github.com/feathersjs/feathers-docs/blob/master/examples/step/01/websocket/1.js). If this snippet is intended for the client side, doesn't that mean the data is still being sent and could still be read by a malicious user, since the data isn't being filtered until it is received?

**Comment by eddyystop** [comment]
That snippet belongs on the server.

We defined a service with `this.use('/users', service({ Model: userModel() }));` and so `users = app.service('users');`

I make it a bit clearer.

**Comment by eddyystop** [comment]
Clarified in https://github.com/feathersjs/feathers-docs/pull/604

**Comment by EnFinlay** [comment]
Thanks for the clarification @eddyystop!
