### ISSUE TITLE
Comment:Step-Basic-Hooks-1

### ISSUE THREAD

**Issue by bitsoflogic** [feathersjs/feathers-docs#607]
Comment:Step-Basic-Hooks-1

Loving the new guide! 

https://docs.feathersjs.com/guides/step-by-step/basic-feathers/hooks-1.html#-userservicebefore-- 

I'm assuming this is synchronous, but not 100% yet... are the hooks run here run synchronously or asynchronously??

**Comment by eddyystop** [comment]
Hooks are run sequentially whether they are sync or asyn. The next hook starts only when the present one finishes.


Sent from my Samsung device

-------- Original message --------

**Comment by eddyystop** [comment]
Let me know if I can close this or not.

**Comment by bitsoflogic** [comment]
Thanks for the clarity.
