### ISSUE TITLE
How to populate DB during the boot?

### ISSUE THREAD

**Issue by AndreMaz** [feathersjs/feathers-docs#611]
How to populate a DB in boot time? Is there any guide about how to do it? 

I've found the [feathers-bootstrap](https://github.com/daffl/feathers-bootstrap) but it seems that this package does not provide a way (or at least it don't explain how) to populate the DB
How can we extend the feathers' bootstrapper to achieve this?

**Comment by daffl** [comment]
You can use https://github.com/thosakwe/feathers-seeder or write your own script by requiring the application:

```js
const app = require('src/app');

app.service('users').create({
  email: 'test@example.com',
  password: 'test'
})then(user => {
  app.service('messages').create({
    text: 'Hello world',
    user: user._id
  })
});
```

**Comment by brandiqa** [comment]
This is the method that I use. Create a file `src/bootstrap.js` and place your data population code. Here's an example that batch imports json data:

```js
const artistsData = require('../mockdata/artists.json');

module.exports = async function (app) {
  const artistService = app.service('artists');
  const artists = await artistService.find();
  if (artists.total == 0) {
    console.log("Populating Artists Table...")
    artistsData.forEach(async (artist) => {
      try {
        let result = await artistService.create(artist)
      } catch (error) {
        console.log(error)
      }
    });
  }
}
```

Next update `src/app.js` by including the following statements:

```js
const bootstrap = require('./bootstrap');
...
// Pre-populate database if empty
app.configure(bootstrap);

module.exports = app;
```

Save the files and restart. You should have your database populated with data.

**Comment by geleto** [comment]
I tried the [brandiqa](https://github.com/brandiqa) suggestion, but it did not work for me because the initialization is asynchronous and when the populate function is called, the `artists` service has not been initialized yet.
