### ISSUE TITLE
Comment:Chat-Authentication

### ISSUE THREAD

**Issue by Herobone** [feathersjs/feathers-docs#612]
I have a problem. Everytime when I try to do this in Postman:

POST "localhost:3030/authentication"
`{
	"strategy": "local",
	"email": "feathers@example.com",
	"password": "secret"
}`

it returns:
`{
  "name": "BadRequest",
  "message": "Authentication strategy 'local' is not registered.",
  "code": 400,
  "className": "bad-request",
  "errors": {}
}`

The same happens if I try this from front-end and from curl

Additional I have finished the tutorial. But there is no possibility to authenticate...
Could sb please help me? I'm new in NodeJS. Previously I just coded in PHP, a little bit JS, css and HTML

Herobone

**Comment by daffl** [comment]
Did you select the "Username + Password (Local)" option when [generating authentication](https://docs.feathersjs.com/guides/chat/authentication.html#generating-authentication)?

**Comment by Herobone** [comment]
Yep

**Comment by marshallswain** [comment]
Please post the contents of `authentication.js`.

**Comment by rehmanShafi** [comment]
Having same issue....
contents of authentication.js in my case..
`const authentication = require('feathers-authentication');`
`const jwt = require('feathers-authentication-jwt');`
`module.exports = function () {`
   `const app = this;`
   `const config = app.get('authentication');`

  `// Set up authentication with the secret`
  `app.configure(authentication(config));`
  `app.configure(jwt());`

  `// The authentication service is used to create a JWT.`
  `// The before create hook registers strategies that can be used`
  `// to create a new valid JWT (e.g. local or oauth2)`
  `app.service('authentication').hooks({`
    `before: {`
      `create: [`
       ` authentication.hooks.authenticate(config.strategies)`
     ` ],`
     ` remove: [`
       ` authentication.hooks.authenticate('jwt')`
      `]`
    `}`
  `});`
`};`
PS: am new to feathers and just following the guideline provided.

**Comment by marshallswain** [comment]
The local strategy isn't configured in that code you posted, @ray-man.

I just tried this with the current generator and it's configured correctly for me:

```js
const authentication = require('feathers-authentication');
const jwt = require('feathers-authentication-jwt');
const local = require('feathers-authentication-local');


module.exports = function () {
  const app = this;
  const config = app.get('authentication');

  // Set up authentication with the secret
  app.configure(authentication(config));
  app.configure(jwt());
  app.configure(local(config.local)); // You're missing this

  // The `authentication` service is used to create a JWT.
  // The before `create` hook registers strategies that can be used
  // to create a new valid JWT (e.g. local or oauth2)
  app.service('authentication').hooks({
    before: {
      create: [
        authentication.hooks.authenticate(config.strategies)
      ],
      remove: [
        authentication.hooks.authenticate('jwt')
      ]
    }
  });
};
```

**Comment by ekryski** [comment]
@ray-man did Marshall's answer fix your problem?

**Comment by tranquill** [comment]
Hello, I seem to be having the same issue. Using what I believe is the latest version of feathers-cli ( 2.2.4): `feathers g authentication` in the shell and selected only the defaults.

The generated authentication.js does not include either
`const local = require('feathers-authentication-local');`
or
`app.configure(local(config.local));`

If I insert those lines manually then it won't start: `Error: Cannot find module 'feathers-authentication-local'`. Yet that module is listed under the devDependencies in the package.json of the feathers-authentication folder.

Sorry if this has an obvious fix. I'm just following the guide and don't know what I'm doing.

**Comment by PierreGallet** [comment]
Hi, first thanks for helping us. Feathers looks fabulous 👍 

I was having the same issue and I added
`const local = require('feathers-authentication-local');`
and
`app.configure(local(config.local));`
lines to my authentication.js file, as suggested @marshallswain 

Then I ran npm install feathers-authentication-local --save, as it was neither on the dependencies nor in the devDependencies. And it worked.

Hope that will help anyone following the tutorial feathers-app.

**Comment by daffl** [comment]
This keeps coming up so to make sure there wasn't a bug that snuck in I re-ran with the latest CLI (v2.3.0) and everything was working fine. The only explanation I have is that people keep forgetting to *confirm the local authentication prompt with the space key* but it does [state that in the guide](https://docs.feathersjs.com/guides/chat/authentication.html#generating-authentication):

> In this guide we will only cover local authentication so let's select the first entry using the Space key and then confirm the selection with enter.

One solution would be to make the selection the default so you can continue by just pressing enter.

**Comment by tranquill** [comment]
Thank you for the reply. That clears it up. 

I would suggest changing the guide so that "using the Space key" is in bold. Those following the guide just did the app and service generator steps, so it's natural to skim this section thinking it should be the same routine. Just need to bring the reader's attention to it.
