### ISSUE TITLE
guides/chat/authentication.html client.configure feathers.authentication 

### ISSUE THREAD

**Issue by kfern** [feathersjs/feathers-docs#615]
Hi!

I'm new with feathers. I think I followed the chat guide steps correctly. Everything works fine until:

> can be used by adding this to public/app.js:

```
client.configure(feathers.authentication({
  storage: window.localStorage
}));
```
Where should I put it? Before or after... 

`client.configure(feathers.socketio(socket)); `

I get the following error message in console:

**Uncaught Error: It looks like feathers-hooks isn't configured. It is required before running feathers-authentication.**
    at Object.<anonymous> (https://npmcdn.com/feathers-client@2.2.0/dist/feathers.js:887:15)
    at https://npmcdn.com/feathers-client@2.2.0/dist/feathers.js:3381:17
    at Array.forEach (native)
    at Object.service (https://npmcdn.com/feathers-client@2.2.0/dist/feathers.js:3380:17)
    at Object.service (https://npmcdn.com/feathers-client@2.2.0/dist/feathers.js:3369:21)
    at http://localhost:3030/app.js:35:25
    
Any ideas?

**Comment by marshallswain** [comment]
You need to configure the hooks plugin before the authentication plugin.

**Comment by marshallswain** [comment]
https://docs.feathersjs.com/api/client.html#load-from-cdn-with-script

**Comment by kfern** [comment]
Everything is working now! Thank you for the help
