### ISSUE TITLE
Discuss: Move Rest Authentication information from /rest/ into authentication

### ISSUE THREAD

**Issue by teddy-error** [feathersjs/feathers-docs#616]
Personally, I struggled a great deal implementing JWT with Feathers on the client side with and I never thought to look in api/rest for information about authenticating, though I wish I had in hindsight. **The authentication page only makes reference to the feathers-client and curl methods of passing a JWT token**, so I found myself consulting external resources on the proper protocol and eventually found a working solution by much trial and error. (e.g. hmm, does it need the Bearer syntax? Is it not working because cookies are off? "no auth found" oh, maybe the token should be named auth... etc)

Of course, in hindsight, the solution was quite a 'duh'.

I only stumbled across the authentication information within api/REST today by coincidence, but it would have been much help. FWIW I see this topic asked in Slack regularly so I think it would be helpful to have more information about a real-world usage rather than or in addition to the CURL way.

I'd be willing to set up a PR for this if it's wanted by others

**Comment by marshallswain** [comment]
Which information, specifically?  I don't see anything in api/rest about auth other than a mention of how to use the `request` module's defaults.

**Comment by marshallswain** [comment]
@teddy-error could you shine some light on this for me?
