### ISSUE TITLE
Comment:Step-Basic-Hooks-1

### ISSUE THREAD

**Issue by jwahdatehagh** [feathersjs/feathers-docs#645]
Comment:Step-Basic-Hooks-1

Hi there, i'm working through the examples section in the documentation and i think the validation hook [here](https://github.com/feathersjs/feathers-docs/blob/master/examples/step/01/hooks/1.js) doesn't work:

When submitting a password that doesn't meet the requirements or omit the password completely, the user still gets created without errors.

Also, when starting the server i get this error `DEPRECATED. Use discard. (remove)` which i wasn't able to track down. I also get `Feathers application started on port 3030` and everything else seems to work fine...

**Comment by eddyystop** [comment]
Oh my, it looks like some temp code was left behind. Try the following and let me know the results.

Could you remove the comment to have
```javascript
 const {
    setCreatedAt, setUpdatedAt, unless, remove, validateSchema
  } = commonHooks;
```
and remove this function
```javascript
function validateSchema() { // todo replace
  return hook => hook;
}
```

The `remove` hook has been deprecated recently in favor of `discard` because we are wanting to eliminate the "magic" hidden in `remove`. https://docs.feathersjs.com/api/hooks-common.html#discard
I'll make an issue for that. Thanks.

**Comment by jwahdatehagh** [comment]
Omg, srry i didn't spot that myself ^_^ Hehe...

Yeah like this it works - you just have to also update the frontend example code in `examples/step/01/common/public/feathers-app.js` to conform with the schema:

```
users.create({ email: 'jane.doe@gmail.com', password: '11111111111' }),
  users.create({ email: 'john.doe@gmail.com', password: '22222222222' }),
  users.create({ email: 'judy.doe@gmail.com', password: '33333333333' })
```

Want me to update and open a PR? 
Thanks again!

**Comment by eddyystop** [comment]
I love PRs! Could you update the example code as well as the docs?

**Comment by jwahdatehagh** [comment]
Ok will do 👍

**Comment by jwahdatehagh** [comment]
Ignore #18f271e ...
