### ISSUE TITLE
Comment:Chat-Authentication

### ISSUE THREAD

**Issue by nickvlku** [feathersjs/feathers-docs#652]
Looks like the client's `app.js` does not configure hooks which, once auth is added, causes the app to throw this client side error:

`Error: It looks like feathers-hooks isn't configured. It is required before running feathers-authentication`

I added one line to `public/app.js` to fix this:

 ```js
client.configure(feathers.socketio(socket));
client.configure(feathers.authentication({
  storage: window.localStorage
}));
client.configure(feathers.hooks()); // <--- this line
``` 
I was going to open a PR to fix the docs, but wasn't sure if this was the right solution since I'm new to Feathers development (hence trying the tutorials :))

Nice docs btw!  Really impressed with how approachable and accessible they are.  Thanks!

**Comment by marshallswain** [comment]
Ah, thanks for pointing this out.  Somebody else ran into problems by this missing, but I didn't realize it was a problem with the docs.  I've updated the previous page of the chat guide to include hooks: https://github.com/feathersjs/feathers-docs/commit/5312189324d799b1f61edd192c7b672322c4c641

**Comment by marshallswain** [comment]
And thanks for the nice words.  We owe a lot of our approachability to @eddyystop's nice work.
