### ISSUE TITLE
populateTeam hook code is missing?

### ISSUE THREAD

**Issue by kfern** [feathersjs/feathers-docs#656]
Hi!

In Lastest Stable (Auk) -> Guides -> The Generator (CLI) -> Add the populate hook, a populateTeam hook is generated. Do something?

[Search](https://docs.feathersjs.com/api/application.html?q=populateTeam) in documentation only returns one result for populateTeam (the "Add the populate hook" page)

**Comment by eddyystop** [comment]
That's a typo. It should be `populate`.

**Comment by eddyystop** [comment]
The generator added file `/src/hooks/populate-teams.js` in which you would write your custom hook. That file required and used in `/src/services/teams.hooks.js`.

What you put in `populate-teams.js` is up to you. You'd likely use the `populate` hook for DB adapters other than Sequelize. You may decide to use the more performant interal Sequelize populate features for Sequelize.

`populate-teams.js` is a no-op. The intent of the page was to show how to generate a custom hook, not to code a working one.

**Comment by eddyystop** [comment]
Clarified in https://github.com/feathersjs/feathers-docs/pull/658
