### ISSUE TITLE
Comment:Chat-Processing

### ISSUE THREAD

**Issue by paul42** [feathersjs/feathers-docs#663]
is there a closing example to show the finalized version in action? when I run npm start and visit localhost:3030 I don't think there's anywhere to login, so my messages end up showing up from undefined? 

maybe this would be a great spot to show how to throw an error and put in some error handling hooks?

**Comment by marshallswain** [comment]
There is a finalized version of the feathers-chat app written in many front end frameworks: https://github.com/feathersjs/feathers-chat

**Comment by paul42** [comment]
awesome, this is fantastic - could we link this to the docs? I love that it mentions create-react-app, since that's what I've started poking at.

Thanks again!

**Comment by marshallswain** [comment]
I added links to the frameworks page, which is referenced at the end of the last page of the chat guide.
