### ISSUE TITLE
Comment:Step-Basic-Db-connector

### ISSUE THREAD

**Issue by necmettin** [feathersjs/feathers-docs#677]
How to run the code is not explained. It does not state that one must `npm install --save feathers nedb feathers-nedb`.

Also, the link _a common way_ https://docs.feathersjs.com/api/databses/querying.md does not exist.

**Comment by eddyystop** [comment]
I believe the install is covered in https://docs.feathersjs.com/guides/step-by-step/preliminaries.html#install-dependencies-used-by-the-examples

```text
**Install dependencies used by the examples**

cd path/to/feathers-docs/examples/step/01
npm install

This will install the dependencies needed by the Basics examples into /examples/step/01/node_modules.
```

The link has been fixed in https://github.com/feathersjs/feathers-docs/pull/679
