### ISSUE TITLE
Comment:Chat-Processing

### ISSUE THREAD

**Issue by emeagenciadigital** [feathersjs/feathers-docs#680]
It does not ask for user and password so the tutorial is not completed.

**Comment by daffl** [comment]
This will be handled in the framework guides (e.g. [this one](https://blog.feathersjs.com/a-real-time-chat-frontend-with-plain-javascript-and-feathers-34e92bcce386?source=user_profile---------2----------------)) and can also be found in the [feathers-chat](https://github.com/feathersjs/feathers-chat) repository.
