### ISSUE TITLE
Comment:Chat-Service

### ISSUE THREAD

**Issue by kadams54** [feathersjs/feathers-docs#688]
Typo in:

`curl 'http://localhost:3030/messages/' -H 'Content-Type: application/json' --data-binary '{ "name": "Curler", "text": "Hello from the commend line!" }'`

"Hello from the commend line" should be "Hello from the command line".

**Comment by daffl** [comment]
Thank you! You can click the "Edit this page button" to [edit the page](https://github.com/feathersjs/feathers-docs/edit/master/guides/chat/service.md) and submit a PR with the fix. Usually that's much faster than creating a separate issue 😄

**Comment by kadams54** [comment]
Ah, thanks! Yes, a PR would be much preferable. I'll go ahead and close both my typo issues (this and #689 and submit PRs instead.
