### ISSUE TITLE
Comment:Step-Basic-Db-connector

### ISSUE THREAD

**Issue by dukeposey** [feathersjs/feathers-docs#694]
Comment:Step-Basic-Db-connector
The 3 user items are now are in the database,
One too many are(s).
Excellent documentation. Thank you for the hard work it took to produce.

**Comment by eddyystop** [comment]
The DB grows are you run examples. You have to erase `data/` between exercises. Could this be what you are seeing?

**Comment by dukeposey** [comment]
I don't think so.
The sentence is written exactly as I put in the input.
Look for "are in are the database,"
I believe it should read.
"are in the database,"

**Comment by dukeposey** [comment]
Although as I look at the sentence you sent it looks like it should read, "The DB grows as you run examples."

**Comment by eddyystop** [comment]
Gotcha. Fixed in https://github.com/feathersjs/feathers-docs/pull/695

**Comment by dukeposey** [comment]
Good Deal.
I was a Tech Writer in a prior life.
I'll keep my eyes open for the little things.
Overall, great documentation.

**Comment by eddyystop** [comment]
Thanks. It takes so much longer than can be imagined.
