### ISSUE TITLE
Comment:Chat-Frontend

### ISSUE THREAD

**Issue by sfrjrs** [feathersjs/feathers-docs#713]
After updating the /public/index.html and app.js are we supposed to stop the application and re-run "npm start"? I stopped/started the application and I see no form.

Editor: Visual Studio Code
Errors in file /public/app.js
Error Message: [eslint] Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)

Windows 7 / Chrome Version 59.0.3071.115

**Comment by daffl** [comment]
If a normal browser refresh did not do it, a hard browser refresh or clearing the cache and reloading the page should do it.
