### ISSUE TITLE
Comment:Step-Basic-Db-connector

### ISSUE THREAD

**Issue by jntme** [feathersjs/feathers-docs#755]
I'm trying to go through the basics. In chapter '_a database connector_' it says:

> users is the only service we need and it's a database table located at examples/step/data/users.db.

With the actual version the path _data/_ does not exist.

**Comment by jntme** [comment]
Ah it exists; but not as I'd expected it under _/examples/step/_, but under _/examples/step/01/examples/step/data/_ - Maybe that should be more clear?

**Comment by eddyystop** [comment]
Wouldn't that be `/examples/step/01/data/ `?

**Comment by gathrlabs** [comment]
I wasn't able to find the users.db file. The /examples/step/01/data/users.db filepath doesn't exist anymore.

**Comment by eddyystop** [comment]
NeDB creates files when it first opens them. Were you looking for the file before or after running an example? Basically, at which step in the guide did you check the file's existance?
