### ISSUE TITLE
Comment:Chat-Frontend

### ISSUE THREAD

**Issue by corecache** [feathersjs/feathers-docs#771]
In the index.hml, I had to use `socket.io/socket.io.js` instead of `/socket.io/socket.io.js` in order for the browser to find the resource.

**Comment by marshallswain** [comment]
Is your app in a subdirectory, maybe?

**Comment by corecache** [comment]
It "was" in an subdirectory - maybe just leave a note somewhere that subdirectories will break it and needs either ProxyPass and RewriteRule fiddling. I moved it under its own subdomain now.

**Comment by daffl** [comment]
We'd definitely merge a PR with a note but to me this is how any webserver relative URL would work (`../socket.io/socket.io.js` in a subfolder would probably also work).
