### ISSUE TITLE
Comment:Step-Basic-Db-connector

### ISSUE THREAD

**Issue by dfdumaresq** [feathersjs/feathers-docs#772]
Comment:Step-Basic-Db-connector
When I try to run your code in your example, I get:
node ./examples/step/01/db-connector/1.js
module.js:487
    throw err;
    ^

Error: Cannot find module 'feathers/feathers-docs/examples/examples/step/01/db-connector/1.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

I have node --version
v8.1.3

Anything else, I should check?

**Comment by eddyystop** [comment]
what command did you run while in which folder?

**Comment by dfdumaresq** [comment]
I ran
`node ./examples/step/01/db-connector/1.js`

in my home folder where I cloned https://github.com/feathersjs/feathers-docs.

`feathers/feathers-docs/examples/examples/step/01/ `

**Comment by dfdumaresq** [comment]
Here are the results from find on module.js under
`/Users/dfdumaresq/Projects/feathers/feathers-docs/examples/step/01`

`find . -name "module.js" -ls
./node_modules/es3ify/node_modules/esprima-fb/test/module.js
./node_modules/esprima-fb/test/module.js`

**Comment by eddyystop** [comment]
"in my home folder where I cloned https://github.com/feathersjs/feathers-docs.".

you have to be in folder `feathers-docs` to run the example. this may within your home folder.

also don't forget
```text
cd path/to/feathers-docs/examples/step/01
npm install
```

**Comment by dfdumaresq** [comment]
Thanks! I was missing that I needed to run the example from the feathers-doc directory.
