### ISSUE TITLE
Comment:Step-Basic-Rest-client

### ISSUE THREAD

**Issue by csakis** [feathersjs/feathers-docs#773]
Comment:Step-Basic-Rest-client
I have a question, comment on this line of code:
 `const feathersClient = feathers()
     .configure(feathers.rest(serverUrl).fetch(fetch))`
Where is the fetch argument of the fetch method is defined?

**Comment by daffl** [comment]
It is built in by most modern browsers (see [compatibility table](http://caniuse.com/#feat=fetch))

**Comment by csakis** [comment]
I think I understand fetch as an AJAX call, what I was not clear about is the argument in the fetch function. It usually is something like `fetch(url).then(doSomething).catch(err)`
I did not find the definition of the 'fetch' argument anywhere in the code.

Thanks for the quick response, btw.

**Comment by daffl** [comment]
You are telling the REST provider to use the global browser instance of `fetch` (which is the same as `window.fetch`). If will then make the AJAX calls using the `fetch` object that was passed internally.

**Comment by csakis** [comment]
Thanks for the clarification.
I am still working toward the feathers _a-ha_ moment 👍
