### ISSUE TITLE
Comment:Step-Basic-Hooks-2

### ISSUE THREAD

**Issue by gfelot** [feathersjs/feathers-docs#779]
Comment:Step-Basic-Hooks-2

Why do we need to use softDelete only when we not use find ? I don't get it sorry.

**Comment by eddyystop** [comment]
`all: when(hook => hook.method !== 'find', softDelete()),`

`find` was bypassed only because the client code uses a `find` to display *all* the records, so the soft deleted ones can be seen.

In practice `find` would not be excluded.

**Comment by eddyystop** [comment]
I'll close this it looks like the last comment resolved the issue.
