### ISSUE TITLE
Comment:Chat-Authentication

### ISSUE THREAD

**Issue by yenly** [feathersjs/feathers-docs#782]
I'm following the instructions and couldn't create a new user using curl or postman. The response is 404. Are the docs outdated?
{
    "name": "NotFound",
    "message": "Page not found",
    "code": 404,
    "className": "not-found",
    "errors": {}
}

**Comment by daffl** [comment]
The docs should be up to date. Could you provide more information on how this would be reproducable?

**Comment by yenly** [comment]
I restart the app and it works.
