### ISSUE TITLE
Comment:Step-Basic-Rest-client

### ISSUE THREAD

**Issue by lobosan** [feathersjs/feathers-docs#793]
Hi I'm following this [example](https://docs.feathersjs.com/guides/step-by-step/basic-feathers/rest-client.html) but not able to see the expected result, instead having these issues in the console
`rest.html:23 Uncaught ReferenceError: feathers is not defined at rest.html:23`
`feathers-app.js:2 Uncaught ReferenceError: feathersClient is not defined at feathers-app.js:2`

**Comment by eddyystop** [comment]
What folder are you running the command from?

On Mon, Jul 31, 2017 at 10:36 AM, Santiago Galindo <notifications@github.com

**Comment by lobosan** [comment]
Hi @eddyystop thanks for your quick response. Since I was following the previous tutorials, first I cloned the feathers-docs repo, then I cd into that folder and run the command ./examples/step/01/rest/1.js and then ctrl + c and run node ./examples/step/01/rest/2 and opened the url http://localhost:3030/rest.html and then I got the errors shown above.

**Comment by eddyystop** [comment]
It turned out to an issue with some CVhrome extensions.

**Comment by lobosan** [comment]
Yes, the extension "Fair AdBlocker" for blocking ads was the problem
