### ISSUE TITLE
Comment:Step-Basic-Real-time

### ISSUE THREAD

**Issue by lobosan** [feathersjs/feathers-docs#794]
Hi can you please specify in this [section](https://docs.feathersjs.com/guides/step-by-step/basic-feathers/real-time.html) where the following code should go?

```
const users = app.service('users');
users.filter((data, connection) => {
  delete data.password;
  return connection.user ? data : false;
});
```

**Comment by eddyystop** [comment]
It can go anywhere.

A consistent location is discussed in the generator section later on.
