### ISSUE TITLE
Add more 'options' example on validateSchema()

### ISSUE THREAD

**Issue by HelloEdit** [feathersjs/feathers-docs#797]
Hello,

I am new to Ajv, and I do not understand how to put personalized messages on schema validation errors. I think this is a very stupid question, I could have asked about stackOverflow but I guess I'm not the only newbie who asked the question ;)
In any case, really, really great documentation :)

Thanks,

link: [doc](https://docs.feathersjs.com/api/hooks-common.html#validateschema)

**Comment by eddyystop** [comment]
You can use https://github.com/epoberezkin/ajv-i18n#usage for internationalization.

If you need more than that, there is (used to be) an ajv options with which you could inject your own message text. That option is a bit hard to find.

**Comment by HelloEdit** [comment]
Thank you for your help, I would watch later.
Will this be added in the next version of the docs?

**Comment by eddyystop** [comment]
I was wrong when I wrote ajv has an option to inject your own message text. I got confused between ajv and Joi.

I added this to the docs
> **ProTip:** You can consider using [ajv-i18n](https://github.com/epoberezkin/ajv-i18n),
together with the [messages](https://github.com/epoberezkin/ajv#advanced-options)
option, to internationalize your error messages.

I'm not sure how the above would be used with validateSchema. Perhaps validateSchema has to be modified around https://github.com/feathersjs/feathers-hooks-common/blob/master/src/services/validate-schema.js#L65

Could you tell me what you determined when you look into it? Thanks.

**Comment by eddyystop** [comment]
And let's continue this at https://github.com/feathersjs/feathers-hooks-common/issues/242
