### ISSUE TITLE
Comment:Chat-Creating

### ISSUE THREAD

**Issue by ctogonon** [feathersjs/feathers-docs#799]
Hi, sorry for noob question, not sure if this is the right place to ask: how do I resolve error from npm test:

  Feathers application tests
    1) starts and shows the index page
    404
      ✓ shows a 404 HTML page (71ms)
      ✓ shows a 404 JSON error without stack trace

  'contact' service
    ✓ registered the service

  3 passing (440ms)
  1 failing

  1) Feathers application tests starts and shows the index page:
     StatusCodeError: 404 - "{\"name\":\"NotFound\",\"message\":\"Page not found\",\"code\":404,\"className\":\"not-found\",\"errors\":{}}"
      at new StatusCodeError (node_modules/request-promise-core/lib/errors.js:32:15)
      at Request.plumbing.callback (node_modules/request-promise-core/lib/plumbing.js:104:33)
      at Request.RP$callback [as _callback] (node_modules/request-promise-core/lib/plumbing.js:46:31)
      at Request.self.callback (node_modules/request/request.js:188:22)
      at Request.<anonymous> (node_modules/request/request.js:1171:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1091:12)
      at endReadableNT (_stream_readable.js:1045:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by daffl** [comment]
Did you remove the index page?

**Comment by ctogonon** [comment]
By index page do you mean public/index.html ? it's there:
```
➜  backend ls -al
total 544
drwxr-xr-x   16 xtiaan  staff     544 Aug  7 00:10 .
drwxr-xr-x   18 xtiaan  staff     612 Aug  7 01:22 ..
-rw-r--r--    1 xtiaan  staff     214 Aug  6 16:34 .editorconfig
-rw-r--r--    1 xtiaan  staff     334 Aug  6 16:34 .eslintrc.json
-rw-r--r--    1 xtiaan  staff    1853 Aug  6 16:34 .gitignore
-rw-r--r--    1 xtiaan  staff     594 Aug  6 16:34 .npmignore
-rw-r--r--    1 xtiaan  staff    1076 Aug  6 16:34 LICENSE
-rw-r--r--    1 xtiaan  staff    1241 Aug  6 16:34 README.md
drwxr-xr-x    4 xtiaan  staff     136 Aug  7 00:11 config
drwxr-xr-x  436 xtiaan  staff   14824 Aug  6 18:36 node_modules
-rw-r--r--    1 xtiaan  staff  149921 Aug  6 18:36 package-lock.json
-rw-r--r--    1 xtiaan  staff    1294 Aug  6 18:36 package.json
drwxr-xr-x    4 xtiaan  staff     136 Aug  6 16:34 public
drwxr-xr-x   10 xtiaan  staff     340 Aug  6 16:36 src
drwxr-xr-x    4 xtiaan  staff     136 Aug  6 16:36 test
-rw-r--r--    1 xtiaan  staff   97858 Aug  6 16:37 yarn.lock
➜  backend ls -alR public 
total 40
drwxr-xr-x   4 xtiaan  staff    136 Aug  6 16:34 .
drwxr-xr-x  16 xtiaan  staff    544 Aug  7 00:10 ..
-rw-r--r--   1 xtiaan  staff   5533 Aug  6 16:34 favicon.ico
-rw-r--r--   1 xtiaan  staff  11376 Aug  6 16:34 index.html
```

**Comment by ctogonon** [comment]
After some restarting of yarn, all tests passed.
