### ISSUE TITLE
Migrate package docs

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-docs#8]
Move the bulk of the docs in the README files into this repo and simplify the README on each package.

### Packages
- [x] feathers
- [ ] feathers-commons
- [ ] feathers-rest
- [ ] feathers-socketio
- [ ] feathers-primus
- [ ] feathers-socket-commons
- [x] feathers-mongodb
- [x] feathers-mongoose
- [x] feathers-authentication
- [ ] feathers-client
- [x] feathers-nedb
- [x] feathers-memory
- [x] feathers-sequelize
- [x] feathers-knex
- [x] feathers-waterline
- [x] feathers-query-filters
- [ ] feathers-configuration
- [x] generator-feathers
- [ ] generator-feathers-plugin

**Comment by daffl** [comment]
I think we can close this. They should be all in the docs now
