### ISSUE TITLE
Comment:Step-Basic-Db-connector

### ISSUE THREAD

**Issue by sganz** [feathersjs/feathers-docs#806]
Comment:Step-Basic-Db-connector
First line of the example output has - 

> feathers-guide$ node ./examples/step/01/a/1
created Jane Doe item
 { email: 'jane.doe@gmail.com',
.
.
.

Which is not the correct path as shown above, might be from the older guide as -
> node ./examples/step/01/db-connector/1.js

Which is correct and not a big deal at all.

**Comment by eddyystop** [comment]
Thanks.

PR has been pushed.
