### ISSUE TITLE
Comment:Step-Basic-About-Hooks-2

### ISSUE THREAD

**Issue by morphatic** [feathersjs/feathers-docs#808]
Just want to be sure about syntax. For service and method-level hooks, the config uses parentheses after the hook method name. For app and app-level error config, you did NOT use parentheses after the hook method name. i.e.
```
// service/method-level hooks
const myHooks = {
  before: {
    all: hook01()  // uses parentheses!
  }
};
const svc = app.service('svc');
svc.hooks(myHooks);

// app-level error/app hooks
app.hooks({
  before: {
    all: hook02 // does NOT use parentheses!
  },
  error: {
    all: hook00e // does NOT use parentheses!
  }
});
```
Why the difference?

**Comment by eddyystop** [comment]
The service call handler expects the hooks it calls to have the signature `context => {}`. So if you have such a hook you would code `all: myHook`.

You however commonly want to pass params to the hook, such as which field in the record to delete. So you need a signature like `params => context => {}` and code `all: myHook()`.

The common hooks and the Feathers community tend to use the latter signature for consistency. So ity would be best to havd `()` everywhere in the examples.

**Comment by eddyystop** [comment]
Docs have been updated.
