### ISSUE TITLE
Comment:Step-Basic-Writing-Hooks

### ISSUE THREAD

**Issue by pmesgari** [feathersjs/feathers-docs#811]
Comment:Step-Basic-Writing-Hooks

I am trying to write a hook for `/users` service to prevent inserting a user with the same email address multiple times in rethinkdb. Here is my hook, but still the user is inserted into rethinkdb table. I assumed by throwing an error, the operation is broken and it would not allow inserting the user.

```
const myDebugHook = function (hook) {
  r.db('feathers_sales_app_server').table('users').filter(function(doc){
    return doc('email').match("payam@example.com")
  }).run(connection, function(err, cursor) {
    if (err) throw err;
    cursor.toArray(function(err, result) {
        if (err) throw err;
        if (result.length > 0) throw new errors.BadRequest('Bad request', { errors: {
            email: 'Already exists'
          }}
        )
    });
  })

  console.log("Creating a user")
}
```

**Comment by eddyystop** [comment]
First, you are doing a direct DB call instead of using a Feathers service. This is unusual in a Feathers app.

Second your DB call is async but you are not returning the promise, so the following hooks are executed without waiting.
