### ISSUE TITLE
Comment:Step-Generators-App

### ISSUE THREAD

**Issue by danmaz74** [feathersjs/feathers-docs#813]
After generating the empty app I wanted to run it. Maybe I missed this, but on the page I didn't see any suggestion how to do it. I quickly found that I needed to run 

`node src/index.js `

from the app root, but I think it would be useful to add this (initially I try to run index.js from inside my IDE, but it failed because it wasn't run from the root folder).

**Comment by daffl** [comment]
Good point. I added a note that you can run `npm start` to start the generated application.

**Comment by danmaz74** [comment]
@daffl great, thanks. I discovered that a few pages later, but it was frustrating not seeing it right away ;)

**Comment by eddyystop** [comment]
Well, the generated code is not intended to be run at that point. The reader has little idea what was generated or how it works. Running the generated code here provides no benefit.

The guide explains what was generated in detail, and then says how to run it.

I think having readers run the generated code at this point will create more questions in their minds and cause more issues.

**Comment by danmaz74** [comment]
> I think having readers run the generated code at this point will create more questions in their minds and cause more issues.

In this case, readers are programmers, who already followed many similar tutorials, and already know that running the server at that point will just show some filler content. I found this approach in most tutorials and never had problems with it - it's just a way to be reassured that what you did is "working".

**Comment by eddyystop** [comment]
The code works because the generator writes code which works. Consider the opposite scenario, what would someone do if the code didn't run?

Thought was put into the flow of the guide. I'd like to be clear that my concern is that running the code here may cause people to start looking at that code before it's explained. This would slow down the learning process and potentially increase the number of issues.

**Comment by danmaz74** [comment]
@eddyystop I always respect those who do the hard work and of course I'll leave the decision to you, but I can say that having to wait so long before being able to see the "hello world" screen slowed down my own learning - I was getting restless to see something "up". If you really think it's such a big distraction, feel free to remove it.

Anyway, keep up the good work :)
