### ISSUE TITLE
link broken https://docs.feathersjs.com

### ISSUE THREAD

**Issue by pricetula** [feathersjs/feathers-docs#817]
Home page link for documentation redirects to page not found at https://docs.feathersjs.com/

**Comment by daffl** [comment]
Looks like a Netlify deploy went wrong. https://docs.feathersjs.com/ is back up.

Although not ideal, in cases like this you can still browse the same documentation in the markdown files at https://github.com/feathersjs/feathers-docs with [SUMMARY.md](https://github.com/feathersjs/feathers-docs/blob/master/SUMMARY.md) as the entry point.

**Comment by thngdude** [comment]
Thanks @daffl

**Comment by pricetula** [comment]
@daffl Alright thanks mate.
