### ISSUE TITLE
Be more specific on client usage

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-docs#82]
For example, http://docs.feathersjs.com/clients/socket-io.html does not mention that it is for plain websocket usage so it is not clear that you should read this *instead* of using the Feathers client.

**Comment by ekryski** [comment]
What do you think about moving those sections for REST, Primus and Socket.io to guides instead? For example, [this section](http://docs.feathersjs.com/clients/socket-io.html#direct-socket-events). I think it will make the client side much more digestable for people.

**Comment by ekryski** [comment]
Closed by 68bb9ef5e1efc847d4b1889d0cd983f42ab24dc9
