### ISSUE TITLE
Comment:Step-Basic-Db-connector

### ISSUE THREAD

**Issue by delebash** [feathersjs/feathers-docs#822]
Comment:Step-Basic-Db-connector

1. The [service](https://docs.feathersjs.com/guides/step-by-step/basic-feathers/database-connector.html#service-methods) method section doesn't make immediately obvious what the definition of a service is until you click on the link [service methods](https://docs.feathersjs.com/api/services.html#service-methods).  Copy the definition of a service and put it on the service page.  Also on the service page make it clear that app.use defines the service and app.service is used to retrieve the instance defined in app.use.

2. Change in examples `const service = require('feathers-nedb');` to something like `const myService = require('feathers-nedb');`.  For me it was confusing at first I thought service was a convention not just the name of the database adapter or custom service that was being imported.

3. Make that there are two types of services one that is pre-defined by your data-adapter such as the  /customer endpoint maps to your database table customers when you define that service.  The 2nd type of service is a custom service as explained...

If acceptable I can make a pull request.

**Comment by eddyystop** [comment]
1. I do not want to get into the details of a service right away.

2. The `service=` naming is used throughout the documentation and in the examples. The examples would have to be changed and retested. imho this is not worth the effort.

3. Custom services were not mentioned on purpose, Readers are primarily interested in DB services. The guides are a gentile introduction to Feathers and I saw no point complicating things and possibly confusing readers by introducing custom services.

Custom services were to be a seperate chapter.

**Comment by delebash** [comment]
no problem, thanks for the reply
