### ISSUE TITLE
Comment:Chat-Processing

### ISSUE THREAD

**Issue by COLABORATI** [feathersjs/feathers-docs#827]
I do not understand why you are using a ```const``` declaration for something like e.g. ```data``` that is *changed* all the time. Would you please like to explain why are you doing that? Thanks!

**Comment by daffl** [comment]
`const` just means that the variable name can't be _reassigned_. If it is a JavaScript object you can still mutate that object itself. Something like

```js
const o = {};

o.message = 'Hello world';
```

Is still the same object `o`. While something like

```js
const o = {};

o = { message: 'Hello world' };
```

Would fail however. If want to prevent objects from being mutated you'll need something like [Object.freeze](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze).

**Comment by COLABORATI** [comment]
Thank you very much for your explanation, I am digging deeper into newer JavaScript features right now to avoid more questions like these... :)
