### ISSUE TITLE
Comment:Chat-Processing

### ISSUE THREAD

**Issue by davidbiller** [feathersjs/feathers-docs#843]
I wasn't asked what method the hook should be used on.

**Comment by daffl** [comment]
Make you have the latest version of `feathers-cli`. `feathers --version` should show `2.3.7` or later.

When generating the hook make sure you do _not_ pick the "I will add it myself" option. You will then be prompted for the type, service and methods:

<img width="616" alt="screen shot 2017-09-14 at 9 10 58 am" src="https://user-images.githubusercontent.com/338316/30440941-cba2845e-992c-11e7-9a05-d1319470d6e3.png">
