### ISSUE TITLE
Comment:Step-Basic-Db-connector

### ISSUE THREAD

**Issue by amls** [feathersjs/feathers-docs#850]
im trying to run this in my command line (windows) node ./examples/step/01/db-connector/1.js, and it's giving me Error: Cannot find module 'feathers', i'm new and lost sorry thanks!

**Comment by eddyystop** [comment]
Ensure you ran the dependencies while in the correct folder. See https://docs.feathersjs.com/guides/step-by-step/preliminaries.html#install-dependencies-used-by-the-examples . It should log a lot of lines to the console the first time its run.

Then ensure your current folder is the one containing `./examples` before running the command.

**Comment by amls** [comment]
thanks mate! working now!
