### ISSUE TITLE
Plugin to expand subchapters

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-docs#9]
Is there a way to only expand the subchapter of the currently selected chapter? I really like how https://www.ottoproject.io/docs/index.html that @ekryski showed me does it. I found https://github.com/GitbookIO/gitbook/issues/717#issuecomment-118396991 so those may be worth looking into.

**Comment by marshallswain** [comment]
How about this one: https://plugins.gitbook.com/plugin/collapsible-menu

**Comment by marshallswain** [comment]
I just added it to the book.json.  It works exactly like Otto's docs.

**Comment by daffl** [comment]
Awesome! That's exactly it. Thank you.

**Comment by ekryski** [comment]
:+1:
