### ISSUE TITLE
Add how to only make services available internally to the FAQ

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-docs#93]
It is currently somewhat hidden in the [bundled hook](http://docs.feathersjs.com/hooks/bundled.html) section.

**Comment by ekryski** [comment]
I've brought it up in the Services section which shows an example and links to the bundled hook as well, so I don't think we need it in the FAQ.

**Comment by ekryski** [comment]
Closed by a18b6dee8ddcc2f6fb53982baf0a8daefc2cc54a

**Comment by Shadowman4205** [comment]
Hello, 
i have simiral question or same dunno exactly.
I am using react starter kit an isomorfic app.
And i using redux for state. By calling actions i call fetch(url) (GET) where url is for getting data with feathers rest.
But i can type in address bar the url that is in fetch an see what it returns. So every visitor to website can do this, but i do not want it. I tried ur suggestion but with  feathers hooks common, but it is not what i am looking for. Also i do not use authentication , i do not need it i just load dynamic data. Any suggestion how i can make it?Or some examples?

**Comment by eddyystop** [comment]
Why don't you use WebSocket clients, and not configure the server for REST? After all WebSockets >> REST for almost everything.
