### ISSUE TITLE
Create Elm documentation

### ISSUE THREAD

**Issue by benjick** [feathersjs/feathers-docs#99]
Sort of like http://docs.feathersjs.com/guides/jquery.html

I'm creating this issue so I won't forget to do it

**Comment by daffl** [comment]
Do you think you'll get a chance for this some time? I'm thinking of moving the chat guides into their own chapter so I'm just wondering if I should add a placeholder or not.

**Comment by benjick** [comment]
Yeah, it's almost done in my fork, will finish up this weekend

**Comment by daffl** [comment]
@benjick Did you get a chance to work on this more? I'm planning on making some reorganizations in the guide/framework sections. Just wanted to make sure that it doesn't conflict with your branch. If you're too busy you can also push what you have and we can try an finish it up.

**Comment by ekryski** [comment]
@benjick bump. Just checking in. Otherwise I think we'll close this and take your awesome example as contribution.

**Comment by benjick** [comment]
Sorry, I haven't had the time. And I haven't looked at the new Elm version as well might have been nice to show instead
